function Search-GPMCReports {
    <#
    .SYNOPSIS
        Searches for Group Policy settings in GPMC-generated XML reports using wildcard patterns.

    .DESCRIPTION
        This function searches through GPMC (Group Policy Management Console) generated XML report files 
        for settings that match a wildcard pattern. It returns the Group Policy Object (GPO) information, 
        the category/area where the setting was found, and the setting details.
        
        This function is specifically designed for XML files generated by GPMC's "Generate Report" feature,
        which have a different structure than PowerShell-exported GPO data.

    .PARAMETER Path
        The path to the GPMC XML report file to search. Can also be a directory to search all XML files within it.

    .PARAMETER XmlContent
        Array of XML content strings to search through instead of reading from files.

    .PARAMETER SearchString
        The search string to look for. Supports wildcards (*).

    .PARAMETER CaseSensitive
        If specified, performs case-sensitive search. Default is case-insensitive.

    .PARAMETER IncludeAllMatches
        If specified, includes all matching text elements, not just those with meaningful content.

    .PARAMETER MaxResults
        Maximum number of results to return. Default is unlimited (0).

    .PARAMETER Recurse
        If Path is a directory, search recursively through subdirectories.

    .EXAMPLE
        Search-GPMCReports -Path ".\AllPreferences1.xml" -SearchString "*oscdimg*"
        Searches for settings containing "oscdimg" in the specified GPMC XML report.

    .EXAMPLE
        Search-GPMCReports -Path ".\AllPreferences1.xml" -SearchString "*Audiosrv*"
        Searches for settings containing "Audiosrv" in the specified GPMC XML report.

    .EXAMPLE
        Search-GPMCReports -Path "." -SearchString "*password*" -Recurse
        Searches for settings containing "password" in all XML files in the current directory and subdirectories.

    .OUTPUTS
        PSCustomObject[] with properties: GPOName, GPOId, DomainName, CategoryPath, SettingName, SettingValue, Context, SourceFile
    #>
    
    [CmdletBinding(DefaultParameterSetName = 'FilePath')]
    param(
        [Parameter(Mandatory = $true, Position = 0, ParameterSetName = 'FilePath')]
        [ValidateScript({
            if (-not (Test-Path $_)) {
                throw "Path not found: $_"
            }
            if ((Get-Item $_).PSIsContainer) {
                return $true  # Directory is valid
            }
            if ($_ -notmatch '\.xml$') {
                throw "File must be an XML file: $_"
            }
            return $true
        })]
        [string]$Path,

        [Parameter(Mandatory = $true, ParameterSetName = 'XmlContent')]
        [ValidateScript({
            if ($_ -eq $null -or $_.Count -eq 0) {
                throw "XmlContent cannot be null or empty array"
            }
            foreach ($content in $_) {
                if ([string]::IsNullOrWhiteSpace($content)) {
                    throw "XmlContent cannot contain null, empty, or whitespace-only strings"
                }
            }
            return $true
        })]
        [string[]]$XmlContent,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$SearchString,

        [Parameter()]
        [switch]$CaseSensitive,

        [Parameter()]
        [switch]$IncludeAllMatches,

        [Parameter()]
        [int]$MaxResults = 0,

        [Parameter(ParameterSetName = 'FilePath')]
        [switch]$Recurse
    )

    begin {
        Write-Verbose "Starting GPMC report search with pattern: $SearchString"
        $results = @()
        $processedFiles = 0
        $totalMatches = 0
    }

    process {
        try {
            if ($PSCmdlet.ParameterSetName -eq 'FilePath') {
                # Process file path
                $files = @()
                
                if ((Get-Item $Path).PSIsContainer) {
                    # Directory path
                    $searchPath = Join-Path $Path "*.xml"
                    if ($Recurse) {
                        $files = Get-ChildItem -Path $searchPath -Recurse -File
                    } else {
                        $files = Get-ChildItem -Path $searchPath -File
                    }
                    
                    if ($files.Count -eq 0) {
                        Write-Warning "No XML files found in directory: $Path"
                        return
                    }
                    
                    Write-Verbose "Found $($files.Count) XML files to process"
                } else {
                    # Single file
                    $files = @(Get-Item $Path)
                }

                foreach ($file in $files) {
                    Write-Verbose "Processing file: $($file.FullName)"
                    $processedFiles++
                    
                    try {
                        $fileResults = Search-GPMCXmlFile -FilePath $file.FullName -SearchString $SearchString -CaseSensitive:$CaseSensitive -IncludeAllMatches:$IncludeAllMatches
                        
                        if ($fileResults) {
                            $results += $fileResults
                            $totalMatches += $fileResults.Count
                            Write-Verbose "Found $($fileResults.Count) matches in $($file.Name)"
                            
                            if ($MaxResults -gt 0 -and $results.Count -ge $MaxResults) {
                                $results = $results[0..($MaxResults-1)]
                                Write-Warning "Maximum results ($MaxResults) reached. Stopping search."
                                break
                            }
                        }
                    }
                    catch {
                        Write-Error "Failed to process file $($file.FullName): $($_.Exception.Message)"
                    }
                }
            }
            else {
                # Process XML content directly
                if ($XmlContent.Count -eq 0) {
                    Write-Warning "No XML content provided"
                    return @()
                }
                
                for ($i = 0; $i -lt $XmlContent.Count; $i++) {
                    Write-Verbose "Processing XML content block $($i + 1) of $($XmlContent.Count)"
                    $processedFiles++
                    
                    # Skip empty or whitespace-only content for graceful handling
                    if ([string]::IsNullOrWhiteSpace($XmlContent[$i])) {
                        Write-Verbose "Skipping empty XML content block $($i + 1)"
                        continue
                    }
                    
                    try {
                        $contentResults = Search-GPMCXmlContent -XmlString $XmlContent[$i] -SearchString $SearchString -SourceFile "XMLContent_$($i+1)" -CaseSensitive:$CaseSensitive -IncludeAllMatches:$IncludeAllMatches
                        
                        if ($contentResults -and $contentResults.Count -gt 0) {
                            $results += $contentResults
                            $totalMatches += $contentResults.Count
                            Write-Verbose "Found $($contentResults.Count) matches in XML content block $($i + 1)"
                            
                            if ($MaxResults -gt 0 -and $results.Count -ge $MaxResults) {
                                $results = $results[0..($MaxResults-1)]
                                Write-Warning "Maximum results ($MaxResults) reached. Stopping search."
                                break
                            }
                        }
                    }
                    catch {
                        Write-Error "Failed to process XML content block $($i + 1): $($_.Exception.Message)"
                    }
                }
            }
        }
        catch {
            Write-Error "Search operation failed: $($_.Exception.Message)"
            throw
        }
    }

    end {
        Write-Verbose "Search completed. Processed $processedFiles files, found $totalMatches total matches, returning $($results.Count) results."
        return $results
    }
}
