function Search-GPMCReports {
    <#
    .SYNOPSIS
        Searches for Group Policy settings in GPMC-generated XML reports using wildcard patterns.

    .DESCRIPTION
        This function searches through GPMC (Group Policy Management Console) generated XML report files 
        for settings that match a wildcard pattern. It returns the Group Policy Object (GPO) information, 
        the category/area where the setting was found, and the setting details.
        
        This function is specifically designed for XML files generated by GPMC's "Generate Report" feature,
        which have a different structure than PowerShell-exported GPO data.

    .PARAMETER Path
        The path to the GPMC XML report file to search. Can also be a directory to search all XML files within it.

    .PARAMETER GpoFilter
        Query Active Directory for GPOs matching this filter (supports wildcards). GPOs will be exported to a 
        temporary directory, searched, and then cleaned up automatically. Requires GroupPolicy module (RSAT).

    .PARAMETER XmlContent
        Array of XML content strings to search through instead of reading from files.

    .PARAMETER SearchString
        The search string to look for. Supports wildcards (*).

    .PARAMETER CaseSensitive
        If specified, performs case-sensitive search. Default is case-insensitive.

    .PARAMETER IncludeAllMatches
        If specified, includes all matching text elements, not just those with meaningful content.

    .PARAMETER MaxResults
        Maximum number of results to return. Default is unlimited (0).

    .PARAMETER IncludeChildDuplicates
        Include child element duplicates when parent and child elements match the same search term.
        By default, child duplicates are filtered out to avoid showing the same logical setting twice.

    .PARAMETER Recurse
        If Path is a directory, search recursively through subdirectories.

    .PARAMETER Domain
        Specify the domain to query when using GpoFilter. If not specified, uses the current domain.

    .EXAMPLE
        Search-GPMCReports -Path ".\AllPreferences1.xml" -SearchString "*oscdimg*"
        Searches for settings containing "oscdimg" in the specified GPMC XML report.

    .EXAMPLE
        Search-GPMCReports -GpoFilter "Default*" -SearchString "*password*"
        Queries Active Directory for all GPOs starting with "Default", exports them temporarily, 
        searches for password-related settings, and cleans up the temporary files.

    .EXAMPLE
        Search-GPMCReports -GpoFilter "*Security*" -SearchString "*audit*" -Domain "contoso.com"
        Searches for audit settings in GPOs containing "Security" in the specified domain.

    .EXAMPLE
        Search-GPMCReports -Path ".\AllPreferences1.xml" -SearchString "*Audiosrv*"
        Searches for settings containing "Audiosrv" in the specified GPMC XML report.

    .EXAMPLE
        Search-GPMCReports -Path "." -SearchString "*password*" -Recurse
        Searches for settings containing "password" in all XML files in the current directory and subdirectories.

    .OUTPUTS
        PSCustomObject[] with properties: GPOName, GPOId, DomainName, CategoryPath, SettingName, 
        SettingValue, Context, Section, Comment, SourceFile, CreatedTime, ModifiedTime, XmlNode
        
        The XmlNode property contains enhanced context information:
        - ElementName: The most meaningful XML element containing the match
        - ElementAttributes: Attributes of the context element  
        - XmlPath: The element name path with namespace
        - OuterXml: Complete XML of the context element
        - ParentHierarchy: Array of parent element names
        - ImmediateParent: The direct parent element of the matched text
        - ContextLevel: "Policy" if meaningful parent found, "Element" if immediate parent used
        - ParsedXml: Structured PowerShell object supporting dot notation access (e.g., $result.XmlNode.ParsedXml.UserRightsAssignment.Name)
        
        The XmlNode property provides enhanced context about where the match was found:
        - ElementName: The most meaningful XML element containing the match (Policy, Account, etc.)
        - ElementAttributes: Attributes of the context element  
        - XmlPath: The element name path with namespace
        - OuterXml: Complete XML of the context element (truncated if > 1000 chars)
        - ParentHierarchy: Array of parent element names (up to 5 levels)
        - ImmediateParent: The direct parent element of the matched text
        - ContextLevel: "Policy" if meaningful parent found, "Element" if immediate parent used
    #>
    
    [CmdletBinding(DefaultParameterSetName = 'FilePath')]
    param(
        [Parameter(Mandatory = $true, Position = 0, ParameterSetName = 'FilePath')]
        [ValidateScript({
            if (-not (Test-Path $_)) {
                throw "Path not found: $_"
            }
            if ((Get-Item $_).PSIsContainer) {
                return $true  # Directory is valid
            }
            if ($_ -notmatch '\.xml$') {
                throw "File must be an XML file: $_"
            }
            return $true
        })]
        [string]$Path,

        [Parameter(Mandatory = $true, ParameterSetName = 'GpoFilter')]
        [ValidateNotNullOrEmpty()]
        [string]$GpoFilter,

        [Parameter(Mandatory = $true, ParameterSetName = 'XmlContent')]
        [AllowEmptyCollection()]
        [AllowEmptyString()]
        [ValidateScript({
            # Allow empty arrays and handle them gracefully in the function
            if ($null -eq $_) {
                throw "XmlContent cannot be null"
            }
            # Allow empty arrays and empty strings to pass validation - we'll handle them in the function logic
            return $true
        })]
        [string[]]$XmlContent,

        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [ValidateScript({
            if ($null -eq $_) {
                throw "SearchString cannot be null"
            }
            # Allow empty strings to pass validation - we'll handle them in the function logic
            return $true
        })]
        [string]$SearchString,

        [Parameter()]
        [switch]$CaseSensitive,

        [Parameter()]
        [switch]$IncludeAllMatches,

        [Parameter()]
        [int]$MaxResults = 0,

        # Include child duplicates (e.g., Properties element when Task element is also found)
        [switch]$IncludeChildDuplicates,

        [Parameter(ParameterSetName = 'FilePath')]
        [switch]$Recurse,

        [Parameter(ParameterSetName = 'GpoFilter')]
        [string]$Domain
    )

    begin {
        Write-Verbose "Starting GPMC report search with pattern: $SearchString"
        
        # Handle empty search string gracefully
        $script:shouldSkipProcessing = [string]::IsNullOrWhiteSpace($SearchString)
        if ($script:shouldSkipProcessing) {
            Write-Warning "Search string is empty or whitespace-only"
        }
        
        $results = @()
        $processedFiles = 0
        $totalMatches = 0
        $tempDirectory = $null
        $exportedXmlFiles = @()
    }

    process {
        # Skip processing if empty search string
        if ($script:shouldSkipProcessing) {
            return
        }
        
        try {
            if ($PSCmdlet.ParameterSetName -eq 'GpoFilter') {
                # Query Active Directory for GPOs and export to temporary directory
                Write-Verbose "Querying Active Directory for GPOs matching filter: $GpoFilter"
                
                # Check if GroupPolicy module is available
                if (-not (Get-Command -Name Get-GPO -ErrorAction SilentlyContinue)) {
                    throw "GroupPolicy module is not available. Please install RSAT Group Policy Management Tools."
                }
                
                # Create temporary directory for GPO exports
                $tempDirectory = Join-Path $env:TEMP "GpoReport_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
                New-Item -Path $tempDirectory -ItemType Directory -Force | Out-Null
                Write-Verbose "Created temporary directory: $tempDirectory"
                
                # Get GPOs from Active Directory
                try {
                    # Get all GPOs and filter by display name (Get-GPO doesn't support wildcards in -Name)
                    $getAllParams = @{
                        All = $true
                        ErrorAction = 'Stop'
                    }
                    if ($Domain) {
                        $getAllParams['Domain'] = $Domain
                    }
                    
                    # Get all GPOs matching the filter (supports wildcards)
                    $gpos = Get-GPO @getAllParams | Where-Object { $_.DisplayName -like $GpoFilter }
                    
                    if ($gpos.Count -gt 0) {
                        Write-Host "Found $($gpos.Count) GPO(s) matching filter"
                    } else {
                        Write-Warning "No GPOs found matching filter: $GpoFilter"
                        return
                    }
                    
                    # Export each GPO to XML
                    foreach ($gpo in $gpos) {
                        $xmlFileName = "$($gpo.DisplayName -replace '[<>:"/\\|?*]', '_').xml"
                        $xmlPath = Join-Path $tempDirectory $xmlFileName

                        Write-Host "Exporting GPO: $($gpo.DisplayName) to $xmlPath"
                        
                        try {
                            $reportParams = @{
                                Guid = $gpo.Id
                                ReportType = 'Xml'
                                Path = $xmlPath
                                ErrorAction = 'Stop'
                            }
                            if ($Domain) {
                                $reportParams['Domain'] = $Domain
                            }
                            
                            Get-GPOReport @reportParams | Out-Null
                            $exportedXmlFiles += $xmlPath
                            Write-Verbose "Successfully exported GPO: $($gpo.DisplayName)"
                        }
                        catch {
                            Write-Warning "Failed to export GPO '$($gpo.DisplayName)': $($_.Exception.Message)"
                            continue
                        }
                    }
                    
                    if ($exportedXmlFiles.Count -eq 0) {
                        Write-Warning "No GPOs were successfully exported"
                        return
                    }
                    
                    Write-Verbose "Successfully exported $($exportedXmlFiles.Count) GPO(s)"
                    
                    # Process exported XML files
                    foreach ($file in $exportedXmlFiles) {
                        Write-Verbose "Processing exported file: $file"
                        $processedFiles++
                        
                        try {
                            $fileResults = Search-GPMCXmlFile -FilePath $file -SearchString $SearchString -CaseSensitive:$CaseSensitive -IncludeAllMatches:$IncludeAllMatches
                            
                            if ($fileResults) {
                                $results += $fileResults
                                $totalMatches += $fileResults.Count
                                Write-Verbose "Found $($fileResults.Count) matches in $(Split-Path $file -Leaf)"
                                
                                if ($MaxResults -gt 0 -and $results.Count -ge $MaxResults) {
                                    $results = $results[0..($MaxResults-1)]
                                    Write-Warning "Maximum results ($MaxResults) reached. Stopping search."
                                    break
                                }
                            }
                        }
                        catch {
                            Write-Warning "Failed to process file $($file): $($_.Exception.Message)"
                            continue
                        }
                    }
                }
                catch {
                    throw "Failed to query Active Directory: $($_.Exception.Message)"
                }
            }
            elseif ($PSCmdlet.ParameterSetName -eq 'FilePath') {
                # Process file path
                $files = @()
                
                if ((Get-Item $Path).PSIsContainer) {
                    # Directory path
                    $searchPath = Join-Path $Path "*.xml"
                    if ($Recurse) {
                        $files = Get-ChildItem -Path $searchPath -Recurse -File
                    } else {
                        $files = Get-ChildItem -Path $searchPath -File
                    }
                    
                    if ($files.Count -eq 0) {
                        Write-Warning "No XML files found in directory: $Path"
                        return
                    }
                    
                    Write-Verbose "Found $($files.Count) XML files to process"
                } else {
                    # Single file
                    $files = @(Get-Item $Path)
                }

                foreach ($file in $files) {
                    Write-Verbose "Processing file: $($file.FullName)"
                    $processedFiles++
                    
                    try {
                        $fileResults = Search-GPMCXmlFile -FilePath $file.FullName -SearchString $SearchString -CaseSensitive:$CaseSensitive -IncludeAllMatches:$IncludeAllMatches
                        
                        if ($fileResults) {
                            $results += $fileResults
                            $totalMatches += $fileResults.Count
                            Write-Verbose "Found $($fileResults.Count) matches in $($file.Name)"
                            
                            if ($MaxResults -gt 0 -and $results.Count -ge $MaxResults) {
                                $results = $results[0..($MaxResults-1)]
                                Write-Warning "Maximum results ($MaxResults) reached. Stopping search."
                                break
                            }
                        }
                    }
                    catch {
                        Write-Warning "Failed to process file $($file.FullName): $($_.Exception.Message)"
                        # Continue processing remaining files even if one fails
                        continue
                    }
                }
            }
            else {
                # Process XML content directly
                if ($XmlContent.Count -eq 0) {
                    Write-Warning "No XML content provided"
                    return @()
                }
                
                for ($i = 0; $i -lt $XmlContent.Count; $i++) {
                    Write-Verbose "Processing XML content block $($i + 1) of $($XmlContent.Count)"
                    $processedFiles++
                    
                    # Skip empty or whitespace-only content for graceful handling
                    if ([string]::IsNullOrWhiteSpace($XmlContent[$i])) {
                        Write-Verbose "Skipping empty XML content block $($i + 1)"
                        continue
                    }
                    
                    try {
                        $contentResults = Search-GPMCXmlContent -XmlString $XmlContent[$i] -SearchString $SearchString -SourceFile "XMLContent_$($i+1)" -CaseSensitive:$CaseSensitive -IncludeAllMatches:$IncludeAllMatches
                        
                        if ($contentResults -and $contentResults.Count -gt 0) {
                            $results += $contentResults
                            $totalMatches += $contentResults.Count
                            Write-Verbose "Found $($contentResults.Count) matches in XML content block $($i + 1)"
                            
                            if ($MaxResults -gt 0 -and $results.Count -ge $MaxResults) {
                                $results = $results[0..($MaxResults-1)]
                                Write-Warning "Maximum results ($MaxResults) reached. Stopping search."
                                break
                            }
                        }
                    }
                    catch {
                        Write-Warning "Failed to process XML content block $($i + 1): $($_.Exception.Message)"
                        # Continue processing remaining blocks even if one fails
                        continue
                    }
                }
            }
        }
        catch {
            Write-Warning "Search operation failed: $($_.Exception.Message)"
            return @()  # Return empty array instead of throwing
        }
    }

    end {
        # Clean up temporary directory if it was created
        if ($tempDirectory -and (Test-Path $tempDirectory)) {
            try {
                Write-Verbose "Cleaning up temporary directory: $tempDirectory"
                Remove-Item -Path $tempDirectory -Recurse -Force -ErrorAction Stop
                Write-Verbose "Temporary directory removed successfully"
            }
            catch {
                Write-Warning "Failed to remove temporary directory '$tempDirectory': $($_.Exception.Message)"
            }
        }
        
        # Return empty array if we skipped processing due to empty search string
        if ($script:shouldSkipProcessing) {
            return @()
        }
        
        # Apply hierarchical deduplication unless specifically disabled
        if (-not $IncludeChildDuplicates -and $results.Count -gt 0) {
            $deduplicatedResults = Remove-HierarchicalDuplicates -Results $results -IncludeChildDuplicates:$IncludeChildDuplicates
            Write-Verbose "Applied deduplication: $($results.Count) original results reduced to $($deduplicatedResults.Count) unique results."
            $results = $deduplicatedResults
        }
        
        Write-Verbose "Search completed. Processed $processedFiles files, found $totalMatches total matches, returning $($results.Count) results."
        return $results
    }
}
