<#
.SYNOPSIS
    Searches for Group Policy settings in GPMC-generated XML reports using wildcard patterns.

.DESCRIPTION
    This script searches through GPMC (Group Policy Management Console) generated XML report files 
    for settings that match a wildcard pattern. It returns the Group Policy Object (GPO) information, 
    the category/area where the setting was found, and the setting details.
    
    This script is specifically designed for XML files generated by GPMC's "Generate Report" feature,
    which have a different structure than PowerShell-exported GPO data.

.PARAMETER Path
    The path to the GPMC XML report file to search. Can also be a directory to search all XML files within it.

.PARAMETER XmlContent
    Array of XML content strings to search through instead of reading from files.

.PARAMETER SearchString
    The search string to look for. Supports wildcards (*).

.PARAMETER CaseSensitive
    If specified, performs case-sensitive search. Default is case-insensitive.

.PARAMETER IncludeAllMatches
    If specified, includes all matching text elements, not just those with meaningful content.

.PARAMETER MaxResults
    Maximum number of results to return. Default is unlimited (0).

.PARAMETER Recurse
    If Path is a directory, search recursively through subdirectories.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path ".\AllPreferences1.xml" -SearchString "*oscdimg*"
    Searches for settings containing "oscdimg" in the specified GPMC XML report.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path ".\AllPreferences1.xml" -SearchString "*Audiosrv*"
    Searches for settings containing "Audiosrv" in the specified GPMC XML report.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path "." -SearchString "*password*" -Recurse
    Searches for settings containing "password" in all XML files in the current directory and subdirectories.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path ".\AllSettings1.xml" -SearchString "*audit*" -MaxResults 10
    Returns up to 10 matches for settings containing "audit".

.EXAMPLE
    $xmlContent = Get-Content ".\AllSettings1.xml" -Raw
    .\Search-GPMCReports.ps1 -XmlContent $xmlContent -SearchString "*cipher*"
    Searches for settings containing "cipher" in the XML content provided as a string.

.EXAMPLE
    $xmlArray = @((Get-Content ".\File1.xml" -Raw), (Get-Content ".\File2.xml" -Raw))
    .\Search-GPMCReports.ps1 -XmlContent $xmlArray -SearchString "*password*"
    Searches for settings containing "password" in multiple XML content strings.
#>

[CmdletBinding(DefaultParameterSetName = 'FilePath')]
param(
    [Parameter(Mandatory = $true, Position = 0, ParameterSetName = 'FilePath')]
    [ValidateScript({
        if (-not (Test-Path $_)) {
            throw "Path not found: $_"
        }
        if ((Get-Item $_).PSIsContainer) {
            return $true  # Directory is valid
        }
        if ($_ -notmatch '\.xml$') {
            throw "File must be XML format"
        }
        return $true
    })]
    [string]$Path,
    
    [Parameter(Mandatory = $true, Position = 0, ParameterSetName = 'XmlContent')]
    [ValidateNotNullOrEmpty()]
    [string[]]$XmlContent,
    
    [Parameter(Mandatory = $true, Position = 1)]
    [string]$SearchString,
    
    [Parameter()]
    [switch]$CaseSensitive,
    
    [Parameter()]
    [switch]$IncludeAllMatches,
    
    [Parameter()]
    [int]$MaxResults = 0,
    
    [Parameter(ParameterSetName = 'FilePath')]
    [switch]$Recurse
)

# Convert wildcard pattern to regex
function ConvertTo-RegexPattern {
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$WildcardPattern,
        
        [Parameter()]
        [bool]$CaseSensitive = $false
    )
    
    # Escape special regex characters except * and ?
    $escaped = [regex]::Escape($WildcardPattern)
    
    # Convert wildcards to regex
    $pattern = $escaped -replace '\\\*', '.*' -replace '\\\?', '.'
    
    if (-not $CaseSensitive) {
        return "(?i)$pattern"
    }
    return $pattern
}

# Extract GPO information from the root GPO element
function Get-GPMCGpoInfo {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlDocument]$XmlDocument,
        
        [Parameter()]
        [string]$SourceFilePath = $null
    )
    
    $gpoInfo = @{
        DisplayName = "Unknown"
        DomainName = "Unknown"  
        GUID = "Unknown"
        CreatedTime = $null
        ModifiedTime = $null
    }
    
    try {
        # Use source file path for display name fallback if provided
        if ($SourceFilePath) {
            $gpoInfo.DisplayName = [System.IO.Path]::GetFileNameWithoutExtension((Split-Path $SourceFilePath -Leaf))
        }
        elseif ($XmlDocument.BaseURI) {
            $gpoInfo.DisplayName = [System.IO.Path]::GetFileNameWithoutExtension((Split-Path $XmlDocument.BaseURI -Leaf))
        }
        
        # Try to get the actual GPO name from XML structure
        $nameElement = $XmlDocument.SelectSingleNode("//*[local-name()='Name' and not(*)]")
        if ($nameElement -and $nameElement.ParentNode.LocalName -eq "GPO") {
            $gpoInfo.DisplayName = $nameElement.InnerText
        }
        
        # Try alternative structure for name
        $nElements = $XmlDocument.SelectNodes("//*[local-name()='n']")
        foreach ($elem in $nElements) {
            if ($elem.ParentNode -and $elem.ParentNode.LocalName -eq "GPO") {
                $gpoInfo.DisplayName = $elem.InnerText
                break
            }
        }
        
        # Get domain and GUID from Identifier section
        $domainElement = $XmlDocument.SelectSingleNode("//*[local-name()='Domain']")
        if ($domainElement) {
            $gpoInfo.DomainName = $domainElement.InnerText
        }
        
        $guidElement = $XmlDocument.SelectSingleNode("//*[local-name()='Identifier' and not(*)]")
        if ($guidElement) {
            $gpoInfo.GUID = $guidElement.InnerText -replace '[{}]', ''
        }
        
        # Get timestamps
        $createdElement = $XmlDocument.SelectSingleNode("//CreatedTime")
        if ($createdElement) {
            $gpoInfo.CreatedTime = $createdElement.InnerText
        }
        
        $modifiedElement = $XmlDocument.SelectSingleNode("//ModifiedTime")
        if ($modifiedElement) {
            $gpoInfo.ModifiedTime = $modifiedElement.InnerText
        }
    }
    catch {
        Write-Verbose "Error extracting GPO info: $($_.Exception.Message)"
    }
    
    return $gpoInfo
}

# Get specific security subcategory based on the element type
function Get-SecuritySubcategory {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlNode]$Node
    )
    
    $currentNode = $Node
    $searchDepth = 0
    
    # Look up the hierarchy to find the security setting type
    while ($null -ne $currentNode -and $searchDepth -lt 10) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            Write-Verbose "Get-SecuritySubcategory: Checking node $($currentNode.LocalName) at depth $searchDepth, namespace: $($currentNode.NamespaceURI)"
            # Check for Security extension namespace
            if ($currentNode.NamespaceURI -eq "http://www.microsoft.com/GroupPolicy/Settings/Security") {
                Write-Verbose "Get-SecuritySubcategory: Found Security namespace for $($currentNode.LocalName)"
                switch ($currentNode.LocalName) {
                    "Account" {
                        # Check the Type element to determine subcategory
                        $typeNode = $currentNode.SelectSingleNode(".//*[local-name()='Type']")
                        if ($typeNode) {
                            switch ($typeNode.InnerText) {
                                "Password" { return "Account Policies > Password Policy" }
                                "Kerberos" { return "Account Policies > Kerberos Policy" }
                                "Lockout" { return "Account Policies > Account Lockout Policy" }
                                default { return "Account Policies" }
                            }
                        }
                        return "Account Policies"
                    }
                    # Check if this is a child of other Security setting types
                    "Name" {
                        if ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "Account") {
                            $typeNode = $currentNode.ParentNode.SelectSingleNode(".//*[local-name()='Type']")
                            if ($typeNode) {
                                switch ($typeNode.InnerText) {
                                    "Password" { return "Account Policies > Password Policy" }
                                    "Kerberos" { return "Account Policies > Kerberos Policy" }
                                    "Lockout" { return "Account Policies > Account Lockout Policy" }
                                    default { return "Account Policies" }
                                }
                            }
                            return "Account Policies"
                        }
                        # Check if this Name is inside a SystemServices element
                        elseif ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "SystemServices") {
                            return "System Services"
                        }
                        # Check if this Name is inside a Member element under UserRightsAssignment
                        elseif ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "Member") {
                            # Look up the hierarchy to find UserRightsAssignment
                            $searchNode = $currentNode.ParentNode
                            while ($null -ne $searchNode -and $searchNode.LocalName -ne "UserRightsAssignment") {
                                $searchNode = $searchNode.ParentNode
                                if ($null -eq $searchNode) { break }
                            }
                            if ($null -ne $searchNode -and $searchNode.LocalName -eq "UserRightsAssignment") {
                                return "Local Policies > User Rights Assignment"
                            }
                        }
                        # Check if this Name is inside a Member element under RestrictedGroups
                        elseif ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "Member") {
                            # Look up the hierarchy to find RestrictedGroups
                            $searchNode = $currentNode.ParentNode
                            while ($null -ne $searchNode -and $searchNode.LocalName -ne "RestrictedGroups") {
                                $searchNode = $searchNode.ParentNode
                                if ($null -eq $searchNode) { break }
                            }
                            if ($null -ne $searchNode -and $searchNode.LocalName -eq "RestrictedGroups") {
                                return "Restricted Groups"
                            }
                        }
                        # Check if this Name is inside a Display element under SecurityOptions
                        elseif ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "Display") {
                            if ($currentNode.ParentNode.ParentNode -and $currentNode.ParentNode.ParentNode.LocalName -eq "SecurityOptions") {
                                # Check for Security Options subcategories based on display name
                                $displayName = $currentNode.InnerText
                                if ($displayName -like "Devices:*") {
                                    return "Local Policies > Security Options > Devices"
                                } elseif ($displayName -like "*SPN target name*") {
                                    # Special case for Server SPN settings - categorize as "Other"
                                    return "Local Policies > Security Options > Other"
                                } elseif ($displayName -like "Domain controller:*") {
                                    # Special case for Domain Controller settings
                                    return "Local Policies > Security Options > Domain Controller"
                                } elseif ($displayName -like "*network client:*" -or $displayName -like "*network server:*") {
                                    return "Local Policies > Security Options > Network"
                                } elseif ($displayName -like "Network*") {
                                    return "Local Policies > Security Options > Network"
                                } elseif ($displayName -like "Interactive logon:*") {
                                    return "Local Policies > Security Options > Interactive Logon"
                                } elseif ($displayName -like "User Account Control:*") {
                                    return "Local Policies > Security Options > User Account Control"
                                } elseif ($displayName -like "System cryptography:*") {
                                    return "Local Policies > Security Options > System Cryptography"
                                } else {
                                    # Default to "Other" for unmatched Security Options
                                    return "Local Policies > Security Options > Other"
                                }
                            }
                        }
                        # Check if this is inside a text node that might contain domain controller settings keywords
                        else {
                            $nodeText = $currentNode.InnerText
                            if ($nodeText -like "*signing*" -or $nodeText -like "*LDAP*" -or $nodeText -like "*Require signing*") {
                                # Look up to see if this is under SecurityOptions
                                $searchNode = $currentNode
                                while ($null -ne $searchNode -and $searchNode.LocalName -ne "SecurityOptions") {
                                    $searchNode = $searchNode.ParentNode
                                    if ($null -eq $searchNode) { break }
                                }
                                if ($null -ne $searchNode -and $searchNode.LocalName -eq "SecurityOptions") {
                                    return "Local Policies > Security Options > Domain Controller"
                                }
                            }
                        }
                    }
                    "DisplayString" {
                        # DisplayString element can contain security option values
                        $displayText = $currentNode.InnerText
                        if ($displayText -like "*signing*" -or $displayText -like "*LDAP*" -or $displayText -like "*Require signing*") {
                            # Look up to see if this is under SecurityOptions
                            $searchNode = $currentNode
                            while ($null -ne $searchNode -and $searchNode.LocalName -ne "SecurityOptions") {
                                $searchNode = $searchNode.ParentNode
                                if ($null -eq $searchNode) { break }
                            }
                            if ($null -ne $searchNode -and $searchNode.LocalName -eq "SecurityOptions") {
                                return "Local Policies > Security Options > Domain Controller"
                            }
                        }
                    }
                    "KeyName" {
                        # KeyName is a child of SecurityOptions
                        if ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "SecurityOptions") {
                            return "Local Policies > Security Options"
                        }
                    }
                    "SystemAccessPolicyName" {
                        # SystemAccessPolicyName is a child of SecurityOptions
                        if ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "SecurityOptions") {
                            return "Local Policies > Security Options"
                        }
                    }
                    "Path" {
                        # Path element can be a child of Registry or File
                        if ($currentNode.ParentNode) {
                            if ($currentNode.ParentNode.LocalName -eq "Registry") {
                                return "Registry"
                            } elseif ($currentNode.ParentNode.LocalName -eq "File") {
                                return "File System"
                            }
                        }
                    }
                    "Audit" {
                        # Check the audit name to determine if it's Account Policies or Local Policies
                        $auditNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name']")
                        if ($auditNameNode) {
                            $auditName = $auditNameNode.InnerText
                            # AuditDSAccess should be under Account Policies
                            if ($auditName -like "*DSAccess*" -or $auditName -like "*Directory Service*") {
                                return "Account Policies > Audit Policy"
                            }
                        }
                        return "Local Policies > Audit Policy"
                    }
                    "UserRightsAssignment" {
                        return "Local Policies > User Rights Assignment"
                    }
                    "EventLog" {
                        return "Event Log"
                    }
                    # Check if we're in any hierarchy that contains UserRightsAssignment
                    default {
                        # Look for UserRightsAssignment anywhere up the chain
                        $searchNode = $currentNode
                        while ($null -ne $searchNode) {
                            if ($searchNode.LocalName -eq "UserRightsAssignment") {
                                return "Local Policies > User Rights Assignment"
                            }
                            $searchNode = $searchNode.ParentNode
                        }
                        # Look for RestrictedGroups anywhere up the chain
                        $searchNode = $currentNode
                        while ($null -ne $searchNode) {
                            if ($searchNode.LocalName -eq "RestrictedGroups") {
                                return "Restricted Groups"
                            }
                            $searchNode = $searchNode.ParentNode
                        }
                        return "Security Settings"
                    }
                }
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    return $null
}

# Get specific audit subcategory based on the subcategory name
function Get-AuditSubcategory {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlNode]$Node
    )
    
    $currentNode = $Node
    $searchDepth = 0
    
    # Look up the hierarchy to find the audit setting type
    while ($null -ne $currentNode -and $searchDepth -lt 10) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            # Check for Auditing extension namespace
            if ($currentNode.NamespaceURI -eq "http://www.microsoft.com/GroupPolicy/Settings/Auditing") {
                switch ($currentNode.LocalName) {
                    "SubcategoryName" {
                        # Determine subcategory based on the audit subcategory name
                        $subcategoryName = $currentNode.InnerText
                        if ($subcategoryName -like "*Kerberos*") {
                            return "Account Logon"
                        } elseif ($subcategoryName -like "*Directory Service*") {
                            return "DS Access"
                        } elseif ($subcategoryName -like "*Logon*" -or $subcategoryName -like "*Account Logon*") {
                            return "Account Logon"
                        } elseif ($subcategoryName -like "*Object Access*") {
                            return "Object Access"
                        } elseif ($subcategoryName -like "*Policy Change*") {
                            return "Policy Change"
                        } elseif ($subcategoryName -like "*Privilege Use*") {
                            return "Privilege Use"
                        } elseif ($subcategoryName -like "*Process*") {
                            return "Detailed Tracking"
                        } elseif ($subcategoryName -like "*System*") {
                            return "System"
                        } else {
                            return "Advanced Audit Configuration"
                        }
                    }
                    "AuditSetting" {
                        # Look for SubcategoryName within AuditSetting
                        $subcategoryNode = $currentNode.SelectSingleNode(".//*[local-name()='SubcategoryName']")
                        if ($subcategoryNode) {
                            $subcategoryName = $subcategoryNode.InnerText
                            if ($subcategoryName -like "*Kerberos*") {
                                return "Account Logon"
                            } elseif ($subcategoryName -like "*Directory Service*") {
                                return "DS Access"
                            } elseif ($subcategoryName -like "*Logon*" -or $subcategoryName -like "*Account Logon*") {
                                return "Account Logon"
                            } elseif ($subcategoryName -like "*Object Access*") {
                                return "Object Access"
                            } elseif ($subcategoryName -like "*Policy Change*") {
                                return "Policy Change"
                            } elseif ($subcategoryName -like "*Privilege Use*") {
                                return "Privilege Use"
                            } elseif ($subcategoryName -like "*Process*") {
                                return "Detailed Tracking"
                            } elseif ($subcategoryName -like "*System*") {
                                return "System"
                            } else {
                                return "Advanced Audit Configuration"
                            }
                        }
                        return "Advanced Audit Configuration"
                    }
                    default {
                        return "Advanced Audit Configuration"
                    }
                }
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    return $null
}

# Get the category/extension name for a matched node
function Get-GPMCCategoryPath {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlNode]$Node,
        
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlDocument]$XmlDocument
    )
    
    $pathElements = @()
    $currentNode = $Node
    $searchDepth = 0
    
    Write-Verbose "Starting category search for node: $($Node.LocalName)"
    
    # First, look for specific policy category in the current hierarchy (for Registry extension)
    $tempNode = $Node
    while ($null -ne $tempNode -and $searchDepth -lt 15) {
        if ($tempNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            # Look for q3:Category element (for Registry extension policies)
            # Only search immediate children, not descendants, to avoid finding unrelated categories
            foreach ($child in $tempNode.ChildNodes) {
                if ($child.LocalName -eq "Category" -and -not [string]::IsNullOrWhiteSpace($child.InnerText)) {
                    $pathElements += $child.InnerText
                    Write-Verbose "Found Policy category: $($child.InnerText)"
                    break
                }
            }
            
            # If we found a category, break out
            if ($pathElements.Count -gt 0) {
                break
            }
        }
        $tempNode = $tempNode.ParentNode
        $searchDepth++
    }
    
    # Reset for extension search
    $currentNode = $Node
    $searchDepth = 0
    
    # Look up the hierarchy to find the ExtensionData container and detect extension type
    while ($null -ne $currentNode -and $searchDepth -lt 20) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            Write-Verbose "Checking node: $($currentNode.LocalName) at depth $searchDepth"
            
            # Check if we've reached an ExtensionData element
            if ($currentNode.LocalName -eq "ExtensionData") {
                # Look for the <n> element that describes this extension
                # Check all child nodes since namespaces can be tricky
                foreach ($child in $currentNode.ChildNodes) {
                    if (($child.LocalName -eq "n" -or $child.LocalName -eq "Name") -and -not [string]::IsNullOrWhiteSpace($child.InnerText)) {
                        $extensionName = $child.InnerText
                        Write-Verbose "Found ExtensionData category: $extensionName"
                        
                        # For Security extension, provide more specific categorization
                        if ($extensionName -eq "Security" -and $pathElements.Count -eq 0) {
                            Write-Verbose "Calling Get-SecuritySubcategory for Security extension"
                            $securityCategory = Get-SecuritySubcategory -Node $Node
                            Write-Verbose "Security subcategory result: '$securityCategory'"
                            if ($securityCategory) {
                                $pathElements += "Security Settings > $securityCategory"
                            } else {
                                $pathElements += "Security Settings"
                            }
                        } 
                        # For Advanced Audit Configuration extension, provide specific categorization
                        elseif ($extensionName -eq "Advanced Audit Configuration" -and $pathElements.Count -eq 0) {
                            Write-Verbose "Calling Get-AuditSubcategory for Advanced Audit Configuration extension"
                            $auditCategory = Get-AuditSubcategory -Node $Node
                            Write-Verbose "Audit subcategory result: '$auditCategory'"
                            if ($auditCategory) {
                                $pathElements += "Security Settings > Advanced Audit Configuration > $auditCategory"
                            } else {
                                $pathElements += "Security Settings > Advanced Audit Configuration"
                            }
                        }
                        # For Registry extension, add Administrative Templates prefix to category
                        elseif ($extensionName -eq "Registry" -and $pathElements.Count -gt 0) {
                            # Category was already found from q3:Category element, add Administrative Templates prefix
                            # Replace / with > for consistency
                            $categoryPath = $pathElements[0] -replace '/', ' > '
                            $pathElements[0] = "Administrative Templates > $categoryPath"
                        }
                        else {
                            # Only add extension name if we don't already have a more specific category
                            if ($pathElements.Count -eq 0) {
                                $pathElements += $extensionName
                            }
                        }
                        break
                    }
                }
                break
            }
            
            # Also check for Computer/User section context
            if ($currentNode.LocalName -eq "Computer") {
                $pathElements += "Computer Configuration"
                Write-Verbose "Found Computer Configuration context"
            }
            elseif ($currentNode.LocalName -eq "User") {
                $pathElements += "User Configuration"
                Write-Verbose "Found User Configuration context"
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    Write-Verbose "Found path elements: $($pathElements -join ', ')"
    
    # Reverse to get path from root to current
    if ($pathElements.Count -gt 0) {
        [Array]::Reverse($pathElements)
    }
    
    # Add specific setting context if available, but not for Security extension settings
    # that already have proper subcategorization
    $settingContext = Get-GPMCSettingContext -Node $Node
    $hasSecuritySubcategory = ($pathElements.Count -gt 0 -and $pathElements[0] -like "Security Settings > *")
    
    if ($settingContext -and -not $hasSecuritySubcategory -and ($pathElements.Count -eq 0 -or $settingContext -ne $pathElements[-1])) {
        $pathElements += $settingContext
        Write-Verbose "Added setting context: $settingContext"
    }
    
    $result = if ($pathElements.Count -gt 0) { 
        ($pathElements -join " > ") 
    } else { 
        "Unknown" 
    }
    
    Write-Verbose "Final category path: $result"
    return $result
}

# Get specific setting context (like the specific policy/preference type)
function Get-GPMCSettingContext {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlNode]$Node
    )
    
    $currentNode = $Node
    $searchDepth = 0
    
    while ($null -ne $currentNode -and $searchDepth -lt 10) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            
            # Look for various setting containers and their identifying attributes
            $nodeName = $currentNode.LocalName
            
            # Check for common GPMC setting types based on element names and attributes
            switch -Regex ($nodeName) {
                "NTService" { 
                    $serviceName = $currentNode.GetAttribute("name")
                    if ($serviceName) { return "Service: $serviceName" }
                    return "Windows Service"
                }
                "Task" { 
                    $taskName = $currentNode.GetAttribute("name")
                    if ($taskName) { return "Scheduled Task: $taskName" }
                    return "Scheduled Task"
                }
                "EnvironmentVariable" { 
                    $varName = $currentNode.GetAttribute("name")
                    if ($varName) { return "Environment Variable: $varName" }
                    return "Environment Variable"
                }
                "File" { 
                    $fileName = $currentNode.GetAttribute("name")
                    if ($fileName) { return "File: $fileName" }
                    return "File Setting"
                }
                "Registry" { 
                    $regName = $currentNode.GetAttribute("name")
                    if ($regName) { return "Registry: $regName" }
                    return "Registry Setting"
                }
                "Group" { 
                    $groupName = $currentNode.GetAttribute("name")
                    if ($groupName) { return "Local Group: $groupName" }
                    return "Local Group"
                }
                "User" { 
                    $userName = $currentNode.GetAttribute("name")
                    if ($userName) { return "Local User: $userName" }
                    return "Local User"
                }
                "DataSource" { 
                    $dsName = $currentNode.GetAttribute("name")
                    if ($dsName) { return "ODBC Data Source: $dsName" }
                    return "ODBC Data Source"
                }
                "Ini" { 
                    $iniName = $currentNode.GetAttribute("name")
                    if ($iniName) { return "INI File Setting: $iniName" }
                    return "INI File Setting"
                }
                "^(Extension|Properties)$" {
                    # Don't use these as context, continue looking
                }
                default {
                    # For other elements, check if they have a name attribute
                    $name = $currentNode.GetAttribute("name")
                    if ($name -and $name -ne $Node.InnerText) {
                        return "$nodeName`: $name"
                    }
                }
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    return $null
}

# Get GPO section (Computer or User) from a node
function Get-GPOSection {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlNode]$Node
    )
    
    $currentNode = $Node
    $searchDepth = 0
    
    # Traverse up the hierarchy to find Computer or User section
    while ($null -ne $currentNode -and $searchDepth -lt 20) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            Write-Verbose "Get-GPOSection: Checking node $($currentNode.LocalName) at depth $searchDepth"
            
            if ($currentNode.LocalName -eq "Computer") {
                Write-Verbose "Get-GPOSection: Found Computer section"
                return "Computer"
            } elseif ($currentNode.LocalName -eq "User") {
                Write-Verbose "Get-GPOSection: Found User section"
                return "User"
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    Write-Verbose "Get-GPOSection: No Computer or User section found after $searchDepth levels"
    return "Unknown"
}

# Get setting details from the matched node and its context
function Get-GPMCSettingDetails {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlNode]$Node
    )
    
    $details = @{
        Name = "Unknown"
        State = "Unknown" 
        Value = $null
        Action = $null
        Type = $null
        Context = $null
        Comment = $null
    }
    
    $currentNode = $Node
    $searchDepth = 0
    
    # Look for setting properties in the current node and nearby context
    while ($null -ne $currentNode -and $searchDepth -lt 15) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            
            # Check current node attributes
            $attributes = @{}
            foreach ($attr in $currentNode.Attributes) {
                $attributes[$attr.Name] = $attr.Value
            }
            
            # Extract meaningful attributes
            if ($attributes.ContainsKey("name") -and $details.Name -eq "Unknown") {
                $details.Name = $attributes["name"]
            }
            if ($attributes.ContainsKey("status") -and $details.State -eq "Unknown") {
                $details.State = $attributes["status"]
            }
            if ($attributes.ContainsKey("action") -and $null -eq $details.Action) {
                $details.Action = $attributes["action"]
            }
            if ($attributes.ContainsKey("value") -and $null -eq $details.Value) {
                $details.Value = $attributes["value"]
            }
            if ($attributes.ContainsKey("type") -and $null -eq $details.Type) {
                $details.Type = $attributes["type"]
            }
            
            # Check for specific element types to determine context
            switch ($currentNode.LocalName) {
                "Policy" {
                    # Look for Policy Name
                    $policyNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($policyNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $policyNameNode.InnerText
                    }
                    
                    # Look for Policy State
                    $policyStateNode = $currentNode.SelectSingleNode(".//*[local-name()='State'][1]")
                    if ($policyStateNode -and $details.State -eq "Unknown") {
                        $details.State = $policyStateNode.InnerText
                    }
                    
                    # Look for Policy Comment
                    $policyCommentNode = $currentNode.SelectSingleNode(".//*[local-name()='Comment'][1]")
                    if ($policyCommentNode -and [string]::IsNullOrWhiteSpace($details.Comment)) {
                        $details.Comment = $policyCommentNode.InnerText
                    }
                    
                    $details.Context = "Group Policy Setting"
                }
                "Account" {
                    # Security Account Policy (Password, Kerberos, etc.)
                    $accountNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($accountNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $accountNameNode.InnerText
                    }
                    
                    $accountNumberNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingNumber'][1]")
                    if ($accountNumberNode -and $details.State -eq "Unknown") {
                        $details.State = $accountNumberNode.InnerText
                    }
                    
                    $accountTypeNode = $currentNode.SelectSingleNode(".//*[local-name()='Type'][1]")
                    if ($accountTypeNode -and $null -eq $details.Type) {
                        $details.Type = $accountTypeNode.InnerText
                    }
                    
                    $details.Context = "Security Account Policy"
                }
                "Audit" {
                    # Security Audit Policy
                    $auditNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($auditNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $auditNameNode.InnerText
                    }
                    
                    $successNode = $currentNode.SelectSingleNode(".//*[local-name()='SuccessAttempts'][1]")
                    $failureNode = $currentNode.SelectSingleNode(".//*[local-name()='FailureAttempts'][1]")
                    if ($successNode -and $failureNode -and $details.State -eq "Unknown") {
                        $success = $successNode.InnerText.ToLower() -eq "true"
                        $failure = $failureNode.InnerText.ToLower() -eq "true"
                        if ($success -and $failure) {
                            $details.State = "Success and Failure"
                        } elseif ($success) {
                            $details.State = "Success"
                        } elseif ($failure) {
                            $details.State = "Failure"
                        } else {
                            $details.State = "No Auditing"
                        }
                    }
                    
                    $details.Context = "Security Audit Policy"
                }
                "UserRightsAssignment" {
                    # Security User Rights Assignment
                    $rightsNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($rightsNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $rightsNameNode.InnerText
                    }
                    
                    $details.Context = "Security User Rights"
                }
                "SecurityOptions" {
                    # Security Options
                    $keyNameNode = $currentNode.SelectSingleNode(".//*[local-name()='KeyName'][1]")
                    if ($keyNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $keyNameNode.InnerText
                    }
                    
                    $settingStringNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingString'][1]")
                    $settingNumberNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingNumber'][1]")
                    if ($settingStringNode -and $details.State -eq "Unknown") {
                        $details.State = $settingStringNode.InnerText
                    } elseif ($settingNumberNode -and $details.State -eq "Unknown") {
                        $details.State = $settingNumberNode.InnerText
                    }
                    
                    # Look for Display Name which is more user-friendly
                    $displayNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Display']//*[local-name()='Name'][1]")
                    if ($displayNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $displayNameNode.InnerText
                    }
                    
                    $details.Context = "Security Options"
                }
                "SystemServices" {
                    # Security System Services
                    $serviceNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($serviceNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $serviceNameNode.InnerText
                    }
                    
                    $startupModeNode = $currentNode.SelectSingleNode(".//*[local-name()='StartupMode'][1]")
                    if ($startupModeNode -and $details.State -eq "Unknown") {
                        $details.State = "Startup: $($startupModeNode.InnerText)"
                    }
                    
                    $details.Context = "Security System Services"
                }
                "File" {
                    # Security File System
                    $pathNode = $currentNode.SelectSingleNode(".//*[local-name()='Path'][1]")
                    if ($pathNode -and $details.Name -eq "Unknown") {
                        $details.Name = $pathNode.InnerText
                    }
                    
                    $modeNode = $currentNode.SelectSingleNode(".//*[local-name()='Mode'][1]")
                    if ($modeNode -and $details.State -eq "Unknown") {
                        $details.State = $modeNode.InnerText
                    }
                    
                    $details.Context = "Security File System"
                }
                "EventLog" {
                    # Security Event Log
                    $eventNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    $eventLogNode = $currentNode.SelectSingleNode(".//*[local-name()='Log'][1]")
                    if ($eventNameNode -and $eventLogNode -and $details.Name -eq "Unknown") {
                        $details.Name = "$($eventLogNode.InnerText) - $($eventNameNode.InnerText)"
                    } elseif ($eventNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $eventNameNode.InnerText
                    }
                    
                    $settingNumberNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingNumber'][1]")
                    if ($settingNumberNode -and $details.State -eq "Unknown") {
                        $details.State = $settingNumberNode.InnerText
                    }
                    
                    $details.Context = "Security Event Log"
                }
                "RestrictedGroups" {
                    # Security Restricted Groups
                    $details.Context = "Security Restricted Groups"
                }
                "DropDownList" {
                    # Get dropdown name and selected value
                    $dropdownNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($dropdownNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $dropdownNameNode.InnerText
                    }
                    
                    $dropdownStateNode = $currentNode.SelectSingleNode(".//*[local-name()='State'][1]")
                    if ($dropdownStateNode -and $details.State -eq "Unknown") {
                        $details.State = $dropdownStateNode.InnerText
                    }
                    
                    # Get selected value
                    $valueNode = $currentNode.SelectSingleNode(".//*[local-name()='Value']//*[local-name()='Name'][1]")
                    if ($valueNode -and $null -eq $details.Value) {
                        $details.Value = $valueNode.InnerText
                    }
                    
                    $details.Context = "Policy Option"
                }
                "CheckBox" {
                    $checkboxNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($checkboxNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $checkboxNameNode.InnerText
                    }
                    
                    $checkboxStateNode = $currentNode.SelectSingleNode(".//*[local-name()='State'][1]")
                    if ($checkboxStateNode -and $details.State -eq "Unknown") {
                        $details.State = $checkboxStateNode.InnerText
                    }
                    
                    $details.Context = "Policy Checkbox"
                }
                "Text" {
                    $textNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($textNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $textNameNode.InnerText
                    }
                    $details.Context = "Policy Text Input"
                }
                "Explain" {
                    $details.Context = "Policy Explanation"
                }
                "NTService" { 
                    $serviceName = $currentNode.GetAttribute("name")
                    if ($serviceName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Service: $serviceName" 
                    }
                    $details.Context = "Windows Service"
                }
                "Task" { 
                    $taskName = $currentNode.GetAttribute("name")
                    if ($taskName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Scheduled Task: $taskName" 
                    }
                    $details.Context = "Scheduled Task"
                }
                "EnvironmentVariable" { 
                    $varName = $currentNode.GetAttribute("name")
                    if ($varName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Environment Variable: $varName" 
                    }
                    $details.Context = "Environment Variable"
                }
                "File" { 
                    $fileName = $currentNode.GetAttribute("name")
                    if ($fileName -and $details.Name -eq "Unknown") { 
                        $details.Name = "File: $fileName" 
                    }
                    $details.Context = "File Setting"
                }
                "Registry" { 
                    $regName = $currentNode.GetAttribute("name")
                    if ($regName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Registry: $regName" 
                    }
                    $details.Context = "Registry Setting"
                }
            }
            
            # Look for Properties child element with additional details
            $propertiesElement = $currentNode.SelectSingleNode(".//*[local-name()='Properties']")
            if ($propertiesElement) {
                foreach ($attr in $propertiesElement.Attributes) {
                    switch ($attr.Name) {
                        "name" { 
                            if ($details.Name -eq "Unknown") { $details.Name = $attr.Value }
                        }
                        "value" { 
                            if ($null -eq $details.Value) { $details.Value = $attr.Value }
                        }
                        "action" { 
                            if ($null -eq $details.Action) { $details.Action = $attr.Value }
                        }
                        "startupType" {
                            if ($details.State -eq "Unknown") { $details.State = "Startup: $($attr.Value)" }
                        }
                        "enabled" {
                            if ($details.State -eq "Unknown") { 
                                $details.State = if ($attr.Value -eq "1") { "Enabled" } else { "Disabled" }
                            }
                        }
                    }
                }
            }
            
            # Stop if we found meaningful information
            if ($details.Name -ne "Unknown" -and $details.State -ne "Unknown" -and $details.Context) { 
                break 
            }
        }
        
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    # Use the node's inner text as value if no other value was found
    if ($null -eq $details.Value -and -not [string]::IsNullOrWhiteSpace($Node.InnerText)) {
        $details.Value = $Node.InnerText.Trim()
    }
    
    return $details
}

# Process XML content (from string or file)
function Search-GPMCXmlContent {
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlDocument]$XmlDocument,
        
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$RegexPattern,
        
        [Parameter(Mandatory = $true)]
        [bool]$IncludeAllMatches,
        
        [Parameter(Mandatory = $true)]
        [int]$MaxResults,
        
        [Parameter()]
        [string]$SourceIdentifier = "Unknown"
    )
    
    $results = @()
    $resultCount = 0
    
    try {
        Write-Verbose "Processing XML content: $SourceIdentifier"
        
        # Get GPO information once for the entire XML content
        $gpoInfo = Get-GPMCGpoInfo -XmlDocument $XmlDocument -SourceFilePath $SourceIdentifier
        
        # Get all nodes (both text nodes and elements with attributes) for searching
        $searchNodes = $XmlDocument.SelectNodes("//*")
        Write-Verbose "Searching through $($searchNodes.Count) nodes..."
        
        # First pass: collect all potential matches
        $potentialMatches = @()
        
        foreach ($node in $searchNodes) {
            # Check inner text content
            $textContent = $node.InnerText
            $matchFound = $false
            $matchedValue = $null
            $matchType = $null
            
            # Check text content (only for leaf nodes or nodes with short text to avoid duplicates)
            if (-not [string]::IsNullOrWhiteSpace($textContent) -and $textContent.Length -ge 2) {
                # Skip nodes that contain child nodes with text (to avoid duplicates)
                $hasTextChildren = $false
                foreach ($child in $node.ChildNodes) {
                    if ($child.NodeType -eq [System.Xml.XmlNodeType]::Element -and 
                        -not [string]::IsNullOrWhiteSpace($child.InnerText) -and 
                        $child.InnerText.Trim() -ne $textContent.Trim()) {
                        $hasTextChildren = $true
                        break
                    }
                }
                
                if (-not $hasTextChildren -and $textContent -match $RegexPattern) {
                    $matchFound = $true
                    $matchedValue = $textContent.Trim()
                    $matchType = "Text Content"
                }
            }
            
            # Check attributes if no text match found or if including all matches
            if (-not $matchFound -or $IncludeAllMatches) {
                foreach ($attr in $node.Attributes) {
                    if ($attr.Value -match $RegexPattern) {
                        $matchFound = $true
                        $matchedValue = $attr.Value
                        $matchType = "Attribute: $($attr.Name)"
                        break
                    }
                }
            }
            
            if ($matchFound) {
                $potentialMatches += @{
                    Node = $node
                    MatchedValue = $matchedValue
                    MatchType = $matchType
                    TextLength = $textContent.Length
                }
            }
        }
        
        Write-Verbose "Found $($potentialMatches.Count) potential matches, filtering duplicates..."
        
        # Second pass: filter out duplicate/parent matches
        $filteredMatches = @()
        
        foreach ($match in $potentialMatches) {
            $isParentMatch = $false
            $isDuplicateMatch = $false
            
            # Check if this match is a parent of another more specific match
            foreach ($otherMatch in $potentialMatches) {
                if ($match -ne $otherMatch -and $match.TextLength -gt $otherMatch.TextLength) {
                    # Check if the other match's text is contained within this match's text
                    if ($match.MatchedValue -like "*$($otherMatch.MatchedValue)*") {
                        # But prefer Name elements over Type elements
                        $matchNodeName = $match.Node.LocalName
                        $otherNodeName = $otherMatch.Node.LocalName
                        
                        # If the longer match is a Name element and shorter is Type, keep the Name
                        if ($matchNodeName -eq "Name" -and $otherNodeName -eq "Type") {
                            # Don't mark as parent, keep the Name element
                            continue
                        }
                        
                        $isParentMatch = $true
                        break
                    }
                }
                
                # Check for exact duplicates but prefer non-attribute matches
                if ($match -ne $otherMatch -and $match.MatchedValue -eq $otherMatch.MatchedValue) {
                    if ($match.MatchType -like "Attribute:*" -and $otherMatch.MatchType -eq "Text Content") {
                        $isDuplicateMatch = $true
                        break
                    }
                }
            }
            
            # Special handling for NTDS: prioritize System Services over Security Options
            if (-not $isParentMatch -and $match.MatchedValue -like "*NTDS*") {
                $matchCategory = Get-GPMCCategoryPath -Node $match.Node -XmlDocument $XmlDocument
                if ($matchCategory -like "*Security Options*") {
                    # Check if there's a System Services match for the same value
                    foreach ($otherMatch in $potentialMatches) {
                        if ($otherMatch.MatchedValue -eq $match.MatchedValue) {
                            $otherCategory = Get-GPMCCategoryPath -Node $otherMatch.Node -XmlDocument $XmlDocument
                            if ($otherCategory -like "*System Services*") {
                                $isDuplicateMatch = $true
                                break
                            }
                        }
                    }
                }
            }
            
            if (-not $isParentMatch -and -not $isDuplicateMatch) {
                $filteredMatches += $match
            }
        }
        
        Write-Verbose "After filtering: $($filteredMatches.Count) unique matches"
        
        # Third pass: create result objects
        foreach ($match in $filteredMatches) {
            if ($MaxResults -gt 0 -and $resultCount -ge $MaxResults) {
                break
            }
            
            Write-Verbose "Processing match: $($match.MatchType): $($match.MatchedValue.Substring(0, [Math]::Min(50, $match.MatchedValue.Length)))..."
            
            # Get category path
            $categoryPath = Get-GPMCCategoryPath -Node $match.Node -XmlDocument $XmlDocument
            
            # Get setting details
            $settingDetails = Get-GPMCSettingDetails -Node $match.Node
            
            # Get GPO section (Computer or User)
            $gpoSection = Get-GPOSection -Node $match.Node
            
            # Create result object
            $result = [PSCustomObject]@{
                MatchedText = $match.MatchedValue
                MatchType = $match.MatchType
                GPO = [PSCustomObject]@{
                    DisplayName = $gpoInfo.DisplayName
                    DomainName = $gpoInfo.DomainName
                    GUID = $gpoInfo.GUID
                    CreatedTime = $gpoInfo.CreatedTime
                    ModifiedTime = $gpoInfo.ModifiedTime
                }
                Section = $gpoSection
                CategoryPath = if ($categoryPath) { $categoryPath } else { "Unknown" }
                Comment = $settingDetails.Comment
                Setting = [PSCustomObject]@{
                    Name = $settingDetails.Name
                    State = $settingDetails.State
                    Value = $settingDetails.Value
                    Action = $settingDetails.Action
                    Type = $settingDetails.Type
                    Context = $settingDetails.Context
                }
                SourceFile = $SourceIdentifier
                XPath = $match.Node.OuterXml.Substring(0, [Math]::Min(300, $match.Node.OuterXml.Length)) + "..."
            }
            
            $results += $result
            $resultCount++
            
            # Show progress for large searches
            if ($resultCount % 10 -eq 0) {
                Write-Progress -Activity "Searching XML content" -Status "Found $resultCount matches" -PercentComplete -1
            }
        }
    }
    catch {
        Write-Warning "Error processing XML content '$SourceIdentifier': $($_.Exception.Message)"
    }
    
    return $results
}

# Process a single XML file
function Search-GPMCXmlFile {
    param(
        [Parameter(Mandatory = $true)]
        [ValidateScript({Test-Path $_ -PathType Leaf})]
        [string]$FilePath,
        
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$RegexPattern,
        
        [Parameter(Mandatory = $true)]
        [bool]$IncludeAllMatches,
        
        [Parameter(Mandatory = $true)]
        [int]$MaxResults
    )
    
    try {
        Write-Verbose "Processing file: $FilePath"
        
        # Load XML document with encoding handling
        $xmlDoc = New-Object System.Xml.XmlDocument
        try {
            # First try to load directly
            $xmlDoc.Load($FilePath)
        }
        catch {
            Write-Verbose "Direct load failed, trying with encoding fix: $($_.Exception.Message)"
            # If direct load fails, read content and fix encoding declaration
            $content = Get-Content -Path $FilePath -Raw -Encoding UTF8
            # Fix common encoding declaration issues
            $content = $content -replace 'encoding="utf-16"', 'encoding="utf-8"'
            $xmlDoc.LoadXml($content)
        }
        
        # Use the new content processing function
        return Search-GPMCXmlContent -XmlDocument $xmlDoc -RegexPattern $RegexPattern -IncludeAllMatches $IncludeAllMatches -MaxResults $MaxResults -SourceIdentifier $FilePath
    }
    catch {
        Write-Warning "Error processing file '$FilePath': $($_.Exception.Message)"
        return @()
    }
}

# Process XML content from string
function Search-GPMCXmlString {
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$XmlContentString,
        
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$RegexPattern,
        
        [Parameter(Mandatory = $true)]
        [bool]$IncludeAllMatches,
        
        [Parameter(Mandatory = $true)]
        [int]$MaxResults,
        
        [Parameter()]
        [string]$SourceIdentifier = "XML String"
    )
    
    try {
        Write-Verbose "Processing XML string content: $SourceIdentifier"
        
        # Load XML document from string
        $xmlDoc = New-Object System.Xml.XmlDocument
        try {
            # First try to load directly
            $xmlDoc.LoadXml($XmlContentString)
        }
        catch {
            Write-Verbose "Direct load failed, trying with encoding fix: $($_.Exception.Message)"
            # If direct load fails, fix encoding declaration
            $content = $XmlContentString -replace 'encoding="utf-16"', 'encoding="utf-8"'
            $xmlDoc.LoadXml($content)
        }
        
        # Use the new content processing function
        return Search-GPMCXmlContent -XmlDocument $xmlDoc -RegexPattern $RegexPattern -IncludeAllMatches $IncludeAllMatches -MaxResults $MaxResults -SourceIdentifier $SourceIdentifier
    }
    catch {
        Write-Warning "Error processing XML string '$SourceIdentifier': $($_.Exception.Message)"
        return @()
    }
}

try {
    # Convert search string to regex pattern
    $regexPattern = ConvertTo-RegexPattern -WildcardPattern $SearchString -CaseSensitive $CaseSensitive.IsPresent
    Write-Verbose "Using regex pattern: $regexPattern"
    
    # Search through all content based on parameter set
    $allResults = @()
    
    if ($PSCmdlet.ParameterSetName -eq 'FilePath') {
        # Handle file/directory path
        $pathItem = Get-Item -Path $Path
        $xmlFiles = @()
        
        if ($pathItem.PSIsContainer) {
            # Directory - find all XML files
            $searchParams = @{
                Path = $Path
                Filter = "*.xml"
                File = $true
            }
            if ($Recurse) {
                $searchParams.Recurse = $true
            }
            
            $xmlFiles = Get-ChildItem @searchParams | Select-Object -ExpandProperty FullName
            
            if ($xmlFiles.Count -eq 0) {
                Write-Warning "No XML files found in directory: $Path"
                return
            }
            
            Write-Host "Found $($xmlFiles.Count) XML files to search" -ForegroundColor Cyan
        }
        else {
            # Single file
            $xmlFiles = @($pathItem.FullName)
        }
        
        # Search through all files
        foreach ($xmlFile in $xmlFiles) {
            $fileResults = Search-GPMCXmlFile -FilePath $xmlFile -RegexPattern $regexPattern -IncludeAllMatches $IncludeAllMatches.IsPresent -MaxResults $MaxResults
            $allResults += $fileResults
            
            if ($MaxResults -gt 0 -and $allResults.Count -ge $MaxResults) {
                $allResults = $allResults | Select-Object -First $MaxResults
                break
            }
        }
        
        # Display source information
        Write-Host "`n=== GPMC SEARCH RESULTS ===" -ForegroundColor Cyan
        Write-Host "Search Pattern: $SearchString" -ForegroundColor Yellow
        if ($xmlFiles.Count -eq 1) {
            Write-Host "File: $($xmlFiles[0])" -ForegroundColor Yellow
        } else {
            Write-Host "Files: $($xmlFiles.Count) XML files searched" -ForegroundColor Yellow
        }
    }
    elseif ($PSCmdlet.ParameterSetName -eq 'XmlContent') {
        # Handle XML content array
        Write-Host "Found $($XmlContent.Count) XML content strings to search" -ForegroundColor Cyan
        
        # Search through all XML content strings
        for ($i = 0; $i -lt $XmlContent.Count; $i++) {
            $xmlString = $XmlContent[$i]
            $sourceId = "XML Content [$($i + 1)]"
            
            $contentResults = Search-GPMCXmlString -XmlContentString $xmlString -RegexPattern $regexPattern -IncludeAllMatches $IncludeAllMatches.IsPresent -MaxResults $MaxResults -SourceIdentifier $sourceId
            $allResults += $contentResults
            
            if ($MaxResults -gt 0 -and $allResults.Count -ge $MaxResults) {
                $allResults = $allResults | Select-Object -First $MaxResults
                break
            }
        }
        
        # Display source information
        Write-Host "`n=== GPMC SEARCH RESULTS ===" -ForegroundColor Cyan
        Write-Host "Search Pattern: $SearchString" -ForegroundColor Yellow
        Write-Host "Source: $($XmlContent.Count) XML content string(s)" -ForegroundColor Yellow
    }
    
    Write-Host "Search completed. Found $($allResults.Count) matches." -ForegroundColor Green
    
    if ($allResults.Count -eq 0) {
        Write-Warning "No matches found for pattern: $SearchString"
        return
    }
    Write-Host ("-" * 80) -ForegroundColor Gray
    
    $resultNumber = 1
    foreach ($result in $allResults) {
        Write-Host "`n[$resultNumber] MATCH FOUND" -ForegroundColor Green
        Write-Host "Matched Text: " -NoNewline -ForegroundColor White
        Write-Host "$($result.MatchedText)" -ForegroundColor Yellow
        Write-Host "Match Type: " -NoNewline -ForegroundColor White
        Write-Host "$($result.MatchType)" -ForegroundColor Cyan
        
        Write-Host "`nGPO Details:" -ForegroundColor Cyan
        Write-Host "  Display Name: $($result.GPO.DisplayName)" -ForegroundColor White
        Write-Host "  Domain: $($result.GPO.DomainName)" -ForegroundColor White
        Write-Host "  GUID: $($result.GPO.GUID)" -ForegroundColor White
        Write-Host "  Section: $($result.Section)" -ForegroundColor White
        if ($result.GPO.CreatedTime) {
            Write-Host "  Created: $($result.GPO.CreatedTime)" -ForegroundColor White
        }
        if ($result.GPO.ModifiedTime) {
            Write-Host "  Modified: $($result.GPO.ModifiedTime)" -ForegroundColor White
        }
        
        Write-Host "`nSetting Details:" -ForegroundColor Cyan
        Write-Host "  Name: $($result.Setting.Name)" -ForegroundColor White
        Write-Host "  State: $($result.Setting.State)" -ForegroundColor White
        if ($result.Setting.Value) {
            Write-Host "  Value: $($result.Setting.Value)" -ForegroundColor White
        }
        if ($result.Setting.Action) {
            Write-Host "  Action: $($result.Setting.Action)" -ForegroundColor White
        }
        if ($result.Setting.Type) {
            Write-Host "  Type: $($result.Setting.Type)" -ForegroundColor White
        }
        if ($result.Setting.Context) {
            Write-Host "  Context: $($result.Setting.Context)" -ForegroundColor White
        }
        if ($result.Comment) {
            Write-Host "  Comment: $($result.Comment)" -ForegroundColor Yellow
        }
        
        if ($result.CategoryPath -ne "Unknown") {
            Write-Host "`nCategory Path: $($result.CategoryPath)" -ForegroundColor Magenta
        }
        
        if ($xmlFiles.Count -gt 1) {
            Write-Host "`nSource File: $([System.IO.Path]::GetFileName($result.SourceFile))" -ForegroundColor Gray
        }
        
        Write-Host ("-" * 80) -ForegroundColor Gray
        $resultNumber++
    }
    
    # Also return the objects for further processing
    return $allResults
}
catch {
    Write-Error "Error during search: $($_.Exception.Message)"
    throw
}
