<#
.SYNOPSIS
    Searches for Group Policy settings in GPMC-generated XML reports using wildcard patterns.

.DESCRIPTION
    This script searches through GPMC (Group Policy Management Console) generated XML report files 
    for settings that match a wildcard pattern. It returns the Group Policy Object (GPO) information, 
    the category/area where the setting was found, and the setting details.
    
    This script is specifically designed for XML files generated by GPMC's "Generate Report" feature,
    which have a different structure than PowerShell-exported GPO data.

.PARAMETER Path
    The path to the GPMC XML report file to search. Can also be a directory to search all XML files within it.

.PARAMETER SearchString
    The search string to look for. Supports wildcards (*).

.PARAMETER CaseSensitive
    If specified, performs case-sensitive search. Default is case-insensitive.

.PARAMETER IncludeAllMatches
    If specified, includes all matching text elements, not just those with meaningful content.

.PARAMETER MaxResults
    Maximum number of results to return. Default is unlimited (0).

.PARAMETER Recurse
    If Path is a directory, search recursively through subdirectories.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path ".\AllPreferences1.xml" -SearchString "*oscdimg*"
    Searches for settings containing "oscdimg" in the specified GPMC XML report.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path ".\AllPreferences1.xml" -SearchString "*Audiosrv*"
    Searches for settings containing "Audiosrv" in the specified GPMC XML report.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path "." -SearchString "*password*" -Recurse
    Searches for settings containing "password" in all XML files in the current directory and subdirectories.

.EXAMPLE
    .\Search-GPMCReports.ps1 -Path ".\AllSettings1.xml" -SearchString "*audit*" -MaxResults 10
    Returns up to 10 matches for settings containing "audit".
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateScript({
        if (-not (Test-Path $_)) {
            throw "Path not found: $_"
        }
        if ((Get-Item $_).PSIsContainer) {
            return $true  # Directory is valid
        }
        if ($_ -notmatch '\.xml$') {
            throw "File must be XML format"
        }
        return $true
    })]
    [string]$Path,
    
    [Parameter(Mandatory = $true, Position = 1)]
    [string]$SearchString,
    
    [Parameter()]
    [switch]$CaseSensitive,
    
    [Parameter()]
    [switch]$IncludeAllMatches,
    
    [Parameter()]
    [int]$MaxResults = 0,
    
    [Parameter()]
    [switch]$Recurse
)

# Convert wildcard pattern to regex
function ConvertTo-RegexPattern {
    param([string]$WildcardPattern, [bool]$CaseSensitive = $false)
    
    # Escape special regex characters except * and ?
    $escaped = [regex]::Escape($WildcardPattern)
    
    # Convert wildcards to regex
    $pattern = $escaped -replace '\\\*', '.*' -replace '\\\?', '.'
    
    if (-not $CaseSensitive) {
        return "(?i)$pattern"
    }
    return $pattern
}

# Extract GPO information from the root GPO element
function Get-GPMCGpoInfo {
    param($XmlDocument)
    
    $gpoInfo = @{
        DisplayName = "Unknown"
        DomainName = "Unknown"  
        GUID = "Unknown"
        CreatedTime = $null
        ModifiedTime = $null
    }
    
    try {
        # Simple fallback: use filename if we can't extract from XML
        $gpoInfo.DisplayName = [System.IO.Path]::GetFileNameWithoutExtension((Split-Path $XmlDocument.BaseURI -Leaf))
        
        # Try to get the actual GPO name from XML (this may not work due to namespace issues)
        $nElements = $XmlDocument.SelectNodes("//*[local-name()='n']")
        foreach ($elem in $nElements) {
            if ($elem.ParentNode -and $elem.ParentNode.LocalName -eq "GPO") {
                $gpoInfo.DisplayName = $elem.InnerText
                break
            }
        }
        
        # Get domain and GUID from Identifier section
        $domainElement = $XmlDocument.SelectSingleNode("//*[local-name()='Domain']")
        if ($domainElement) {
            $gpoInfo.DomainName = $domainElement.InnerText
        }
        
        $guidElement = $XmlDocument.SelectSingleNode("//*[local-name()='Identifier' and not(*)]")
        if ($guidElement) {
            $gpoInfo.GUID = $guidElement.InnerText -replace '[{}]', ''
        }
        
        # Get timestamps
        $createdElement = $XmlDocument.SelectSingleNode("//CreatedTime")
        if ($createdElement) {
            $gpoInfo.CreatedTime = $createdElement.InnerText
        }
        
        $modifiedElement = $XmlDocument.SelectSingleNode("//ModifiedTime")
        if ($modifiedElement) {
            $gpoInfo.ModifiedTime = $modifiedElement.InnerText
        }
    }
    catch {
        Write-Verbose "Error extracting GPO info: $($_.Exception.Message)"
    }
    
    return $gpoInfo
}

# Get specific security subcategory based on the element type
function Get-SecuritySubcategory {
    param($Node)
    
    $currentNode = $Node
    $searchDepth = 0
    
    # Look up the hierarchy to find the security setting type
    while ($null -ne $currentNode -and $searchDepth -lt 10) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            # Check for Security extension namespace
            if ($currentNode.NamespaceURI -eq "http://www.microsoft.com/GroupPolicy/Settings/Security") {
                switch ($currentNode.LocalName) {
                    "Account" {
                        # Check the Type element to determine subcategory
                        $typeNode = $currentNode.SelectSingleNode(".//*[local-name()='Type']")
                        if ($typeNode) {
                            switch ($typeNode.InnerText) {
                                "Password" { return "Account Policies > Password Policy" }
                                "Kerberos" { return "Account Policies > Kerberos Policy" }
                                "Lockout" { return "Account Policies > Account Lockout Policy" }
                                default { return "Account Policies" }
                            }
                        }
                        return "Account Policies"
                    }
                    # Check if this is a child of an Account node
                    "Name" {
                        if ($currentNode.ParentNode -and $currentNode.ParentNode.LocalName -eq "Account") {
                            $typeNode = $currentNode.ParentNode.SelectSingleNode(".//*[local-name()='Type']")
                            if ($typeNode) {
                                switch ($typeNode.InnerText) {
                                    "Password" { return "Account Policies > Password Policy" }
                                    "Kerberos" { return "Account Policies > Kerberos Policy" }
                                    "Lockout" { return "Account Policies > Account Lockout Policy" }
                                    default { return "Account Policies" }
                                }
                            }
                            return "Account Policies"
                        }
                    }
                    "Audit" {
                        return "Local Policies > Audit Policy"
                    }
                    "UserRightsAssignment" {
                        return "Local Policies > User Rights Assignment"
                    }
                    "SecurityOptions" {
                        return "Local Policies > Security Options"
                    }
                    "EventLog" {
                        return "Event Log"
                    }
                    "RestrictedGroups" {
                        return "Restricted Groups"
                    }
                    "SystemServices" {
                        return "System Services"
                    }
                    "File" {
                        return "File System"
                    }
                    "Registry" {
                        return "Registry"
                    }
                    "Wmi" {
                        return "WMI"
                    }
                    default {
                        return "Security Settings"
                    }
                }
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    return $null
}

# Get the category/extension name for a matched node
function Get-GPMCCategoryPath {
    param($Node, $XmlDocument)
    
    $pathElements = @()
    $currentNode = $Node
    $searchDepth = 0
    
    Write-Verbose "Starting category search for node: $($Node.LocalName)"
    
    # First, look for specific policy category in the current hierarchy (for Registry extension)
    $tempNode = $Node
    while ($null -ne $tempNode -and $searchDepth -lt 15) {
        if ($tempNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            # Look for q3:Category element (for Registry extension policies)
            # Only search immediate children, not descendants, to avoid finding unrelated categories
            foreach ($child in $tempNode.ChildNodes) {
                if ($child.LocalName -eq "Category" -and -not [string]::IsNullOrWhiteSpace($child.InnerText)) {
                    $pathElements += $child.InnerText
                    Write-Verbose "Found Policy category: $($child.InnerText)"
                    break
                }
            }
            
            # If we found a category, break out
            if ($pathElements.Count -gt 0) {
                break
            }
        }
        $tempNode = $tempNode.ParentNode
        $searchDepth++
    }
    
    # Reset for extension search
    $currentNode = $Node
    $searchDepth = 0
    
    # Look up the hierarchy to find the ExtensionData container and detect extension type
    while ($null -ne $currentNode -and $searchDepth -lt 20) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            Write-Verbose "Checking node: $($currentNode.LocalName) at depth $searchDepth"
            
            # Check if we've reached an ExtensionData element
            if ($currentNode.LocalName -eq "ExtensionData") {
                # Look for the <n> element that describes this extension
                # Check all child nodes since namespaces can be tricky
                foreach ($child in $currentNode.ChildNodes) {
                    if (($child.LocalName -eq "n" -or $child.LocalName -eq "Name") -and -not [string]::IsNullOrWhiteSpace($child.InnerText)) {
                        $extensionName = $child.InnerText
                        Write-Verbose "Found ExtensionData category: $extensionName"
                        
                        # For Security extension, provide more specific categorization
                        if ($extensionName -eq "Security" -and $pathElements.Count -eq 0) {
                            Write-Verbose "Calling Get-SecuritySubcategory for Security extension"
                            $securityCategory = Get-SecuritySubcategory -Node $Node
                            Write-Verbose "Security subcategory result: '$securityCategory'"
                            if ($securityCategory) {
                                $pathElements += "Security Settings > $securityCategory"
                            } else {
                                $pathElements += "Security Settings"
                            }
                        } else {
                            # Only add extension name if we don't already have a more specific category
                            if ($pathElements.Count -eq 0) {
                                $pathElements += $extensionName
                            }
                        }
                        break
                    }
                }
                break
            }
            
            # Also check for Computer/User section context
            if ($currentNode.LocalName -eq "Computer") {
                $pathElements += "Computer Configuration"
                Write-Verbose "Found Computer Configuration context"
            }
            elseif ($currentNode.LocalName -eq "User") {
                $pathElements += "User Configuration"
                Write-Verbose "Found User Configuration context"
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    Write-Verbose "Found path elements: $($pathElements -join ', ')"
    
    # Reverse to get path from root to current
    if ($pathElements.Count -gt 0) {
        [Array]::Reverse($pathElements)
    }
    
    # Add specific setting context if available
    $settingContext = Get-GPMCSettingContext -Node $Node
    if ($settingContext -and ($pathElements.Count -eq 0 -or $settingContext -ne $pathElements[-1])) {
        $pathElements += $settingContext
        Write-Verbose "Added setting context: $settingContext"
    }
    
    $result = if ($pathElements.Count -gt 0) { 
        ($pathElements -join " > ") 
    } else { 
        "Unknown" 
    }
    
    Write-Verbose "Final category path: $result"
    return $result
}

# Get specific setting context (like the specific policy/preference type)
function Get-GPMCSettingContext {
    param($Node)
    
    $currentNode = $Node
    $searchDepth = 0
    
    while ($null -ne $currentNode -and $searchDepth -lt 10) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            
            # Look for various setting containers and their identifying attributes
            $nodeName = $currentNode.LocalName
            
            # Check for common GPMC setting types based on element names and attributes
            switch -Regex ($nodeName) {
                "NTService" { 
                    $serviceName = $currentNode.GetAttribute("name")
                    if ($serviceName) { return "Service: $serviceName" }
                    return "Windows Service"
                }
                "Task" { 
                    $taskName = $currentNode.GetAttribute("name")
                    if ($taskName) { return "Scheduled Task: $taskName" }
                    return "Scheduled Task"
                }
                "EnvironmentVariable" { 
                    $varName = $currentNode.GetAttribute("name")
                    if ($varName) { return "Environment Variable: $varName" }
                    return "Environment Variable"
                }
                "File" { 
                    $fileName = $currentNode.GetAttribute("name")
                    if ($fileName) { return "File: $fileName" }
                    return "File Setting"
                }
                "Registry" { 
                    $regName = $currentNode.GetAttribute("name")
                    if ($regName) { return "Registry: $regName" }
                    return "Registry Setting"
                }
                "Group" { 
                    $groupName = $currentNode.GetAttribute("name")
                    if ($groupName) { return "Local Group: $groupName" }
                    return "Local Group"
                }
                "User" { 
                    $userName = $currentNode.GetAttribute("name")
                    if ($userName) { return "Local User: $userName" }
                    return "Local User"
                }
                "DataSource" { 
                    $dsName = $currentNode.GetAttribute("name")
                    if ($dsName) { return "ODBC Data Source: $dsName" }
                    return "ODBC Data Source"
                }
                "Ini" { 
                    $iniName = $currentNode.GetAttribute("name")
                    if ($iniName) { return "INI File Setting: $iniName" }
                    return "INI File Setting"
                }
                "^(Extension|Properties)$" {
                    # Don't use these as context, continue looking
                }
                default {
                    # For other elements, check if they have a name attribute
                    $name = $currentNode.GetAttribute("name")
                    if ($name -and $name -ne $Node.InnerText) {
                        return "$nodeName`: $name"
                    }
                }
            }
        }
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    return $null
}

# Get setting details from the matched node and its context
function Get-GPMCSettingDetails {
    param($Node)
    
    $details = @{
        Name = "Unknown"
        State = "Unknown" 
        Value = $null
        Action = $null
        Type = $null
        Context = $null
    }
    
    $currentNode = $Node
    $searchDepth = 0
    
    # Look for setting properties in the current node and nearby context
    while ($null -ne $currentNode -and $searchDepth -lt 15) {
        if ($currentNode.NodeType -eq [System.Xml.XmlNodeType]::Element) {
            
            # Check current node attributes
            $attributes = @{}
            foreach ($attr in $currentNode.Attributes) {
                $attributes[$attr.Name] = $attr.Value
            }
            
            # Extract meaningful attributes
            if ($attributes.ContainsKey("name") -and $details.Name -eq "Unknown") {
                $details.Name = $attributes["name"]
            }
            if ($attributes.ContainsKey("status") -and $details.State -eq "Unknown") {
                $details.State = $attributes["status"]
            }
            if ($attributes.ContainsKey("action") -and $null -eq $details.Action) {
                $details.Action = $attributes["action"]
            }
            if ($attributes.ContainsKey("value") -and $null -eq $details.Value) {
                $details.Value = $attributes["value"]
            }
            if ($attributes.ContainsKey("type") -and $null -eq $details.Type) {
                $details.Type = $attributes["type"]
            }
            
            # Check for specific element types to determine context
            switch ($currentNode.LocalName) {
                "Policy" {
                    # Look for Policy Name
                    $policyNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($policyNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $policyNameNode.InnerText
                    }
                    
                    # Look for Policy State
                    $policyStateNode = $currentNode.SelectSingleNode(".//*[local-name()='State'][1]")
                    if ($policyStateNode -and $details.State -eq "Unknown") {
                        $details.State = $policyStateNode.InnerText
                    }
                    
                    $details.Context = "Group Policy Setting"
                }
                "Account" {
                    # Security Account Policy (Password, Kerberos, etc.)
                    $accountNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($accountNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $accountNameNode.InnerText
                    }
                    
                    $accountNumberNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingNumber'][1]")
                    if ($accountNumberNode -and $details.State -eq "Unknown") {
                        $details.State = $accountNumberNode.InnerText
                    }
                    
                    $accountTypeNode = $currentNode.SelectSingleNode(".//*[local-name()='Type'][1]")
                    if ($accountTypeNode -and $null -eq $details.Type) {
                        $details.Type = $accountTypeNode.InnerText
                    }
                    
                    $details.Context = "Security Account Policy"
                }
                "Audit" {
                    # Security Audit Policy
                    $auditNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($auditNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $auditNameNode.InnerText
                    }
                    
                    $successNode = $currentNode.SelectSingleNode(".//*[local-name()='SuccessAttempts'][1]")
                    $failureNode = $currentNode.SelectSingleNode(".//*[local-name()='FailureAttempts'][1]")
                    if ($successNode -and $failureNode -and $details.State -eq "Unknown") {
                        $success = $successNode.InnerText.ToLower() -eq "true"
                        $failure = $failureNode.InnerText.ToLower() -eq "true"
                        if ($success -and $failure) {
                            $details.State = "Success and Failure"
                        } elseif ($success) {
                            $details.State = "Success"
                        } elseif ($failure) {
                            $details.State = "Failure"
                        } else {
                            $details.State = "No Auditing"
                        }
                    }
                    
                    $details.Context = "Security Audit Policy"
                }
                "UserRightsAssignment" {
                    # Security User Rights Assignment
                    $rightsNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($rightsNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $rightsNameNode.InnerText
                    }
                    
                    $details.Context = "Security User Rights"
                }
                "SecurityOptions" {
                    # Security Options
                    $keyNameNode = $currentNode.SelectSingleNode(".//*[local-name()='KeyName'][1]")
                    if ($keyNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $keyNameNode.InnerText
                    }
                    
                    $settingStringNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingString'][1]")
                    $settingNumberNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingNumber'][1]")
                    if ($settingStringNode -and $details.State -eq "Unknown") {
                        $details.State = $settingStringNode.InnerText
                    } elseif ($settingNumberNode -and $details.State -eq "Unknown") {
                        $details.State = $settingNumberNode.InnerText
                    }
                    
                    # Look for Display Name which is more user-friendly
                    $displayNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Display']//*[local-name()='Name'][1]")
                    if ($displayNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $displayNameNode.InnerText
                    }
                    
                    $details.Context = "Security Options"
                }
                "SystemServices" {
                    # Security System Services
                    $serviceNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($serviceNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $serviceNameNode.InnerText
                    }
                    
                    $startupModeNode = $currentNode.SelectSingleNode(".//*[local-name()='StartupMode'][1]")
                    if ($startupModeNode -and $details.State -eq "Unknown") {
                        $details.State = "Startup: $($startupModeNode.InnerText)"
                    }
                    
                    $details.Context = "Security System Services"
                }
                "File" {
                    # Security File System
                    $pathNode = $currentNode.SelectSingleNode(".//*[local-name()='Path'][1]")
                    if ($pathNode -and $details.Name -eq "Unknown") {
                        $details.Name = $pathNode.InnerText
                    }
                    
                    $modeNode = $currentNode.SelectSingleNode(".//*[local-name()='Mode'][1]")
                    if ($modeNode -and $details.State -eq "Unknown") {
                        $details.State = $modeNode.InnerText
                    }
                    
                    $details.Context = "Security File System"
                }
                "EventLog" {
                    # Security Event Log
                    $eventNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    $eventLogNode = $currentNode.SelectSingleNode(".//*[local-name()='Log'][1]")
                    if ($eventNameNode -and $eventLogNode -and $details.Name -eq "Unknown") {
                        $details.Name = "$($eventLogNode.InnerText) - $($eventNameNode.InnerText)"
                    } elseif ($eventNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $eventNameNode.InnerText
                    }
                    
                    $settingNumberNode = $currentNode.SelectSingleNode(".//*[local-name()='SettingNumber'][1]")
                    if ($settingNumberNode -and $details.State -eq "Unknown") {
                        $details.State = $settingNumberNode.InnerText
                    }
                    
                    $details.Context = "Security Event Log"
                }
                "RestrictedGroups" {
                    # Security Restricted Groups
                    $details.Context = "Security Restricted Groups"
                }
                "DropDownList" {
                    # Get dropdown name and selected value
                    $dropdownNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($dropdownNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $dropdownNameNode.InnerText
                    }
                    
                    $dropdownStateNode = $currentNode.SelectSingleNode(".//*[local-name()='State'][1]")
                    if ($dropdownStateNode -and $details.State -eq "Unknown") {
                        $details.State = $dropdownStateNode.InnerText
                    }
                    
                    # Get selected value
                    $valueNode = $currentNode.SelectSingleNode(".//*[local-name()='Value']//*[local-name()='Name'][1]")
                    if ($valueNode -and $null -eq $details.Value) {
                        $details.Value = $valueNode.InnerText
                    }
                    
                    $details.Context = "Policy Option"
                }
                "CheckBox" {
                    $checkboxNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($checkboxNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $checkboxNameNode.InnerText
                    }
                    
                    $checkboxStateNode = $currentNode.SelectSingleNode(".//*[local-name()='State'][1]")
                    if ($checkboxStateNode -and $details.State -eq "Unknown") {
                        $details.State = $checkboxStateNode.InnerText
                    }
                    
                    $details.Context = "Policy Checkbox"
                }
                "Text" {
                    $textNameNode = $currentNode.SelectSingleNode(".//*[local-name()='Name'][1]")
                    if ($textNameNode -and $details.Name -eq "Unknown") {
                        $details.Name = $textNameNode.InnerText
                    }
                    $details.Context = "Policy Text Input"
                }
                "Explain" {
                    $details.Context = "Policy Explanation"
                }
                "NTService" { 
                    $serviceName = $currentNode.GetAttribute("name")
                    if ($serviceName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Service: $serviceName" 
                    }
                    $details.Context = "Windows Service"
                }
                "Task" { 
                    $taskName = $currentNode.GetAttribute("name")
                    if ($taskName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Scheduled Task: $taskName" 
                    }
                    $details.Context = "Scheduled Task"
                }
                "EnvironmentVariable" { 
                    $varName = $currentNode.GetAttribute("name")
                    if ($varName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Environment Variable: $varName" 
                    }
                    $details.Context = "Environment Variable"
                }
                "File" { 
                    $fileName = $currentNode.GetAttribute("name")
                    if ($fileName -and $details.Name -eq "Unknown") { 
                        $details.Name = "File: $fileName" 
                    }
                    $details.Context = "File Setting"
                }
                "Registry" { 
                    $regName = $currentNode.GetAttribute("name")
                    if ($regName -and $details.Name -eq "Unknown") { 
                        $details.Name = "Registry: $regName" 
                    }
                    $details.Context = "Registry Setting"
                }
            }
            
            # Look for Properties child element with additional details
            $propertiesElement = $currentNode.SelectSingleNode(".//*[local-name()='Properties']")
            if ($propertiesElement) {
                foreach ($attr in $propertiesElement.Attributes) {
                    switch ($attr.Name) {
                        "name" { 
                            if ($details.Name -eq "Unknown") { $details.Name = $attr.Value }
                        }
                        "value" { 
                            if ($null -eq $details.Value) { $details.Value = $attr.Value }
                        }
                        "action" { 
                            if ($null -eq $details.Action) { $details.Action = $attr.Value }
                        }
                        "startupType" {
                            if ($details.State -eq "Unknown") { $details.State = "Startup: $($attr.Value)" }
                        }
                        "enabled" {
                            if ($details.State -eq "Unknown") { 
                                $details.State = if ($attr.Value -eq "1") { "Enabled" } else { "Disabled" }
                            }
                        }
                    }
                }
            }
            
            # Stop if we found meaningful information
            if ($details.Name -ne "Unknown" -and $details.State -ne "Unknown" -and $details.Context) { 
                break 
            }
        }
        
        $currentNode = $currentNode.ParentNode
        $searchDepth++
    }
    
    # Use the node's inner text as value if no other value was found
    if ($null -eq $details.Value -and -not [string]::IsNullOrWhiteSpace($Node.InnerText)) {
        $details.Value = $Node.InnerText.Trim()
    }
    
    return $details
}

# Process a single XML file
function Search-GPMCXmlFile {
    param($FilePath, $RegexPattern, $IncludeAllMatches, $MaxResults)
    
    $results = @()
    $resultCount = 0
    
    try {
        Write-Verbose "Processing file: $FilePath"
        
        # Load XML document
        $xmlDoc = New-Object System.Xml.XmlDocument
        $xmlDoc.Load($FilePath)
        
        # Get GPO information once for the entire file
        $gpoInfo = Get-GPMCGpoInfo -XmlDocument $xmlDoc
        
        # Get all nodes (both text nodes and elements with attributes) for searching
        $searchNodes = $xmlDoc.SelectNodes("//*")
        Write-Verbose "Searching through $($searchNodes.Count) nodes..."
        
        # First pass: collect all potential matches
        $potentialMatches = @()
        
        foreach ($node in $searchNodes) {
            # Check inner text content
            $textContent = $node.InnerText
            $matchFound = $false
            $matchedValue = $null
            $matchType = $null
            
            # Check text content (only for leaf nodes or nodes with short text to avoid duplicates)
            if (-not [string]::IsNullOrWhiteSpace($textContent) -and $textContent.Length -ge 2) {
                # Skip nodes that contain child nodes with text (to avoid duplicates)
                $hasTextChildren = $false
                foreach ($child in $node.ChildNodes) {
                    if ($child.NodeType -eq [System.Xml.XmlNodeType]::Element -and 
                        -not [string]::IsNullOrWhiteSpace($child.InnerText) -and
                        $child.InnerText -match $RegexPattern) {
                        $hasTextChildren = $true
                        break
                    }
                }
                
                if (-not $hasTextChildren -and $textContent -match $RegexPattern) {
                    $matchFound = $true
                    $matchedValue = $textContent.Trim()
                    $matchType = "Text Content"
                }
            }
            
            # Check attributes if no text match found or if including all matches
            if (-not $matchFound -or $IncludeAllMatches) {
                foreach ($attr in $node.Attributes) {
                    if ($attr.Value -match $RegexPattern) {
                        if (-not $matchFound) {
                            $matchFound = $true
                            $matchedValue = $attr.Value
                            $matchType = "Attribute: $($attr.Name)"
                        } elseif ($IncludeAllMatches) {
                            # Handle multiple matches in same node if including all
                            Write-Verbose "Additional attribute match found: $($attr.Name) = $($attr.Value)"
                        }
                    }
                }
            }
            
            if ($matchFound) {
                $potentialMatches += @{
                    Node = $node
                    MatchedValue = $matchedValue
                    MatchType = $matchType
                    TextLength = $textContent.Length
                }
            }
        }
        
        Write-Verbose "Found $($potentialMatches.Count) potential matches, filtering duplicates..."
        
        # Second pass: filter out duplicate/parent matches
        $filteredMatches = @()
        
        foreach ($match in $potentialMatches) {
            $isParentMatch = $false
            
            # Check if this match is a parent of another more specific match
            foreach ($otherMatch in $potentialMatches) {
                if ($match -ne $otherMatch -and $match.TextLength -gt $otherMatch.TextLength) {
                    # Check if the other match's node is a descendant of this match's node
                    $tempNode = $otherMatch.Node
                    while ($null -ne $tempNode) {
                        if ($tempNode -eq $match.Node) {
                            $isParentMatch = $true
                            Write-Verbose "Filtering out parent match: $($match.MatchedValue.Substring(0, [Math]::Min(50, $match.MatchedValue.Length)))..."
                            break
                        }
                        $tempNode = $tempNode.ParentNode
                    }
                    if ($isParentMatch) { break }
                }
            }
            
            if (-not $isParentMatch) {
                $filteredMatches += $match
            }
        }
        
        Write-Verbose "After filtering: $($filteredMatches.Count) unique matches"
        
        # Third pass: create result objects
        foreach ($match in $filteredMatches) {
            if ($MaxResults -gt 0 -and $resultCount -ge $MaxResults) {
                break
            }
            
            Write-Verbose "Processing match: $($match.MatchType): $($match.MatchedValue.Substring(0, [Math]::Min(50, $match.MatchedValue.Length)))..."
            
            # Get category path
            $categoryPath = Get-GPMCCategoryPath -Node $match.Node -XmlDocument $xmlDoc
            
            # Get setting details
            $settingDetails = Get-GPMCSettingDetails -Node $match.Node
            
            # Create result object
            $result = [PSCustomObject]@{
                MatchedText = $match.MatchedValue
                MatchType = $match.MatchType
                GPO = [PSCustomObject]@{
                    DisplayName = $gpoInfo.DisplayName
                    DomainName = $gpoInfo.DomainName
                    GUID = $gpoInfo.GUID
                    CreatedTime = $gpoInfo.CreatedTime
                    ModifiedTime = $gpoInfo.ModifiedTime
                }
                CategoryPath = if ($categoryPath) { $categoryPath } else { "Unknown" }
                Setting = [PSCustomObject]@{
                    Name = $settingDetails.Name
                    State = $settingDetails.State
                    Value = $settingDetails.Value
                    Action = $settingDetails.Action
                    Type = $settingDetails.Type
                    Context = $settingDetails.Context
                }
                SourceFile = $FilePath
                XPath = $match.Node.OuterXml.Substring(0, [Math]::Min(300, $match.Node.OuterXml.Length)) + "..."
            }
            
            $results += $result
            $resultCount++
            
            # Show progress for large searches
            if ($resultCount % 10 -eq 0) {
                Write-Verbose "Created $resultCount result objects so far..."
            }
        }
    }
    catch {
        Write-Warning "Error processing file '$FilePath': $($_.Exception.Message)"
    }
    
    return $results
}

try {
    # Convert search string to regex pattern
    $regexPattern = ConvertTo-RegexPattern -WildcardPattern $SearchString -CaseSensitive $CaseSensitive.IsPresent
    Write-Verbose "Using regex pattern: $regexPattern"
    
    # Determine if Path is a file or directory
    $pathItem = Get-Item -Path $Path
    $xmlFiles = @()
    
    if ($pathItem.PSIsContainer) {
        # Directory - find all XML files
        $searchParams = @{
            Path = $Path
            Filter = "*.xml"
            File = $true
        }
        if ($Recurse) {
            $searchParams.Recurse = $true
        }
        
        $xmlFiles = Get-ChildItem @searchParams | Select-Object -ExpandProperty FullName
        
        if ($xmlFiles.Count -eq 0) {
            Write-Warning "No XML files found in directory: $Path"
            return
        }
        
        Write-Host "Found $($xmlFiles.Count) XML files to search" -ForegroundColor Cyan
    }
    else {
        # Single file
        $xmlFiles = @($pathItem.FullName)
    }
    
    # Search through all files
    $allResults = @()
    
    foreach ($xmlFile in $xmlFiles) {
        $fileResults = Search-GPMCXmlFile -FilePath $xmlFile -RegexPattern $regexPattern -IncludeAllMatches $IncludeAllMatches.IsPresent -MaxResults $MaxResults
        $allResults += $fileResults
        
        if ($MaxResults -gt 0 -and $allResults.Count -ge $MaxResults) {
            $allResults = $allResults | Select-Object -First $MaxResults
            break
        }
    }
    
    Write-Host "Search completed. Found $($allResults.Count) matches." -ForegroundColor Green
    
    if ($allResults.Count -eq 0) {
        Write-Warning "No matches found for pattern: $SearchString"
        return
    }
    
    # Display results in a readable format
    Write-Host "`n=== GPMC SEARCH RESULTS ===" -ForegroundColor Cyan
    Write-Host "Search Pattern: $SearchString" -ForegroundColor Yellow
    if ($xmlFiles.Count -eq 1) {
        Write-Host "File: $($xmlFiles[0])" -ForegroundColor Yellow
    } else {
        Write-Host "Files: $($xmlFiles.Count) XML files searched" -ForegroundColor Yellow
    }
    Write-Host ("-" * 80) -ForegroundColor Gray
    
    $resultNumber = 1
    foreach ($result in $allResults) {
        Write-Host "`n[$resultNumber] MATCH FOUND" -ForegroundColor Green
        Write-Host "Matched Text: " -NoNewline -ForegroundColor White
        Write-Host "$($result.MatchedText)" -ForegroundColor Yellow
        Write-Host "Match Type: " -NoNewline -ForegroundColor White
        Write-Host "$($result.MatchType)" -ForegroundColor Cyan
        
        Write-Host "`nGPO Details:" -ForegroundColor Cyan
        Write-Host "  Display Name: $($result.GPO.DisplayName)" -ForegroundColor White
        Write-Host "  Domain: $($result.GPO.DomainName)" -ForegroundColor White
        Write-Host "  GUID: $($result.GPO.GUID)" -ForegroundColor White
        if ($result.GPO.CreatedTime) {
            Write-Host "  Created: $($result.GPO.CreatedTime)" -ForegroundColor White
        }
        if ($result.GPO.ModifiedTime) {
            Write-Host "  Modified: $($result.GPO.ModifiedTime)" -ForegroundColor White
        }
        
        Write-Host "`nSetting Details:" -ForegroundColor Cyan
        Write-Host "  Name: $($result.Setting.Name)" -ForegroundColor White
        Write-Host "  State: $($result.Setting.State)" -ForegroundColor White
        if ($result.Setting.Value) {
            Write-Host "  Value: $($result.Setting.Value)" -ForegroundColor White
        }
        if ($result.Setting.Action) {
            Write-Host "  Action: $($result.Setting.Action)" -ForegroundColor White
        }
        if ($result.Setting.Type) {
            Write-Host "  Type: $($result.Setting.Type)" -ForegroundColor White
        }
        if ($result.Setting.Context) {
            Write-Host "  Context: $($result.Setting.Context)" -ForegroundColor White
        }
        
        if ($result.CategoryPath -ne "Unknown") {
            Write-Host "`nCategory Path: $($result.CategoryPath)" -ForegroundColor Magenta
        }
        
        if ($xmlFiles.Count -gt 1) {
            Write-Host "`nSource File: $([System.IO.Path]::GetFileName($result.SourceFile))" -ForegroundColor Gray
        }
        
        Write-Host ("-" * 80) -ForegroundColor Gray
        $resultNumber++
    }
    
    # Also return the objects for further processing
    return $allResults
}
catch {
    Write-Error "Error during search: $($_.Exception.Message)"
    throw
}
