#
# Module manifest for module 'GpoReport'
#
# Generated by: Raimund Andree
#
# Generated on: 8/5/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'GpoReport.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = 'b1234567-89ab-cdef-0123-456789abcdef'

    # Author of this module
    Author            = 'Raimund Andree'

    # Company or vendor of this module
    CompanyName       = 'Unknown'

    # Copyright statement for this module
    Copyright         = '(c) Raimund Andree. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'PowerShell module for searching Group Policy Object (GPO) settings using wildcard patterns, with advanced analysis, export capabilities, and compliance checking.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Search-GPMCReports',
        'Export-SearchResults', 
        'Get-GPOInsights',
        'Search-GPOCompliance',
        'Search-GPOCached',
        'Show-GPOSearchReport',
        'Show-GPOSearchReportUi'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('GPO', 'GroupPolicy', 'Search', 'Security', 'Compliance', 'PowerShell', 'Windows', 'Administration')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/raandree/GpoReport/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/raandree/GpoReport'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
# GpoReport Release Notes

## Version 1.0.0 (Initial Release)

### Features
- **Search-GPMCReports**: Core function to search GPMC XML reports with wildcard patterns
- **Export-SearchResults**: Export search results to multiple formats (JSON, CSV, HTML, XML)
- **Get-GPOInsights**: AI-powered analysis for security, compliance, and performance insights
- **Search-GPOCompliance**: Compliance-focused search with pre-built templates (CIS, NIST, SOX, HIPAA)
- **Search-GPOCached**: High-performance search with intelligent caching and parallel processing
- **Show-GPOSearchReport**: Generate comprehensive HTML reports from GPO search results
- **Show-GPOSearchReportUi**: User-friendly GUI for HTML report generation

### Capabilities
- Wildcard pattern search across GPO XML files
- Multi-format export (JSON, CSV, HTML, XML) with metadata
- Security risk assessment and compliance mapping
- Performance analysis and conflict detection
- Intelligent caching for improved performance
- Interactive GUI for non-technical users
- Support for both GPMC-generated and PowerShell-exported XML files

### Requirements
- PowerShell 5.1 or later
- Windows operating system
- .NET Framework 4.6 or later
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
